export const offlineTitlesFr: Record<string, string> = {
  'implicit-shell': 'Deux champs, une enveloppe échantillonnée',
  'terrain-hit': 'Un rayon rencontre le relief',
  'curve-control': 'Préparer une trajectoire ondulée',
  painted: 'La couleur suit la hauteur',
  'height-palette': 'Une palette pour le relief',
  'hard-edges': 'Une normale par face',
  lettering: 'Deux lettres en blocs originales',
  'uv-tiles': 'Des coordonnées UV déterministes',
  sampling: 'Choisir la densité avant compilation',
  'convex-prism': 'Un solide polygonal convexe',
  prism: 'Six faces, un solide',
  contour: 'Un contour prend du volume',
  ribbon: 'Un tube suit une vague',
  'rational-roof': 'Une toiture pondérée',
  loft: 'Une coque torsadée',
  vessel: 'Un profil devient un vase',
  terrain: 'Un paysage ondulé échantillonné',
  city: 'Une silhouette urbaine déterministe',
  sculpture: 'Une empreinte de brosse préparée',
  refinement: 'Quatre triangles à partir d’un',
  difference: 'Un tunnel dans un solide de voxels',
  indexed: 'Des sommets partagés sur une surface',
  'wide-indices': 'Dépasser les indices sur seize bits',
  'bent-prism': 'Préparer une courbure non linéaire',
};
export const offlineNotesFr: Record<string, string> = {
  'implicit-shell':
    'Faces exposées de voxels issus d’un champ implicite ; ce n’est pas marching cubes.',
  'curve-control': 'Une courbe ondulée préparée, pas un éditeur interactif de splines.',
  sampling:
    'Une densité d’échantillonnage réduite à la création, pas une simplification du maillage.',
  vessel: 'Une surface de révolution originale, pas un modèle de théière.',
  lettering: 'Des lettres en blocs originales, pas un chargeur de polices ni un rendu de contours.',
  'convex-prism': 'Un contour convexe connu, pas un calcul d’enveloppe convexe de points.',
  refinement: 'Un raffinement linéaire par les milieux, pas une subdivision lissante.',
  difference: 'Une différence sur une grille de voxels bornée, pas un booléen exact de maillages.',
  'uv-tiles':
    'Les coordonnées UV sont conservées dans la source ; la scène ne contient pas de texture.',
};
