#!/bin/sh
. "$(dirname "$0")/lib.sh"
case "$(git rev-parse --abbrev-ref HEAD)" in
  [0-9]*-*) ;;
  HEAD) ;; # detached: rebase, bisect, cherry-pick in progress
  *) refuse "commits belong on a branch named <issue>-<short-name>, cut from develop for one GitHub issue." ;;
esac
run_local_hook pre-commit "$@"
