import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {resolve} from 'node:path';
const labRoot=process.env.LAB_ROOT??resolve('../render-tech-lab');
const {chromium}=createRequire(resolve(labRoot,'package.json'))('playwright');
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const page=await browser.newPage();
 await page.goto(process.env.WG_URL??'http://127.0.0.1:5177/test/browser-test.html');
 const result=await page.evaluate(async()=>{
  const {createGpuSmallTriangles}=await import('/packages/sdk-browser/gpuSmallTriangles.ts');
  const {VIS_SHADER}=await import('/packages/sdk-browser/visibilityBuffer.ts');
  const adapter=await navigator.gpu?.requestAdapter();if(!adapter)throw new Error('WEBGPU_ADAPTER_UNAVAILABLE');
  const device=await adapter.requestDevice();const errors=[];device.addEventListener('uncapturederror',event=>errors.push(event.error.message));
  const module=device.createShaderModule({code:VIS_SHADER});const compilation=await module.getCompilationInfo();
  const shaderErrors=compilation.messages.filter(message=>message.type==='error').map(message=>message.message);
  const storage=GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST;
  const write=(values,size=values.byteLength)=>{const buffer=device.createBuffer({size:Math.max(4,size),usage:storage});device.queue.writeBuffer(buffer,0,values);return buffer;};
  const indices=write(new Uint32Array([0,1,2]));
  const positions=write(new Float32Array([-.1,-.1,.5,.1,-.1,.5,0,.1,.5]));
  const uvs=write(new Float32Array(6));
  const flags=write(new Uint32Array([0]));
  const pageData=new ArrayBuffer(256),f=new Float32Array(pageData),u=new Uint32Array(pageData);
  f.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);f[19]=1;u[23]=2;u[24]=0;u[25]=3;u[26]=0;u[27]=1<<16;f[28]=1;f[29]=1;u[31]=0xffffffff;
  const pages=write(new Uint8Array(pageData));
  const uniformData=new Float32Array(20);uniformData.set([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);uniformData[16]=32;uniformData[17]=32;uniformData[18]=7;
  const uniform=device.createBuffer({size:256,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});device.queue.writeBuffer(uniform,0,uniformData);
  const maps=device.createTexture({size:{width:1,height:1,depthOrArrayLayers:2},format:'rgba8unorm-srgb',usage:GPUTextureUsage.TEXTURE_BINDING|GPUTextureUsage.COPY_DST});
  device.queue.writeTexture({texture:maps,origin:[0,0,0]},new Uint8Array([255,255,255,255]),{bytesPerRow:4},[1,1]);
  const ids=device.createTexture({size:[32,32],format:'r32uint',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC});
  const depth=device.createTexture({size:[32,32],format:'depth32float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC});
  device.pushErrorScope('validation');
  const raster=createGpuSmallTriangles(device,32,32);
  const encoder=device.createCommandEncoder();
  const clear=encoder.beginRenderPass({colorAttachments:[{view:ids.createView(),loadOp:'clear',storeOp:'store',clearValue:[0,0,0,0]}],depthStencilAttachment:{view:depth.createView(),depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'store'}});clear.end();
  raster.encode(encoder,{indices,positions,pages,hizFlags:flags,uniform,uvs,maps:maps.createView({dimension:'2d-array'}),sampler:device.createSampler(),pageRows:1,maxTriangles:1,idsView:ids.createView(),depthView:depth.createView()});
  const row=256,readback=device.createBuffer({size:row*32,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});
  const depthReadback=device.createBuffer({size:row*32,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ});
  encoder.copyTextureToBuffer({texture:ids},{buffer:readback,bytesPerRow:row},[32,32]);
  encoder.copyTextureToBuffer({texture:depth},{buffer:depthReadback,bytesPerRow:row},[32,32]);
  device.queue.submit([encoder.finish()]);await device.queue.onSubmittedWorkDone();
  const validation=await device.popErrorScope();
  await readback.mapAsync(GPUMapMode.READ);await depthReadback.mapAsync(GPUMapMode.READ);
  const idsData=new DataView(readback.getMappedRange()),depthData=new DataView(depthReadback.getMappedRange());
  const pixel=(x,y)=>idsData.getUint32(y*row+x*4,true);
  const centerId=pixel(16,16),outerId=pixel(0,0),centerDepth=depthData.getFloat32(16*row+16*4,true);
  const output={shaderErrors,validation:validation?.message??null,errors,centerId,outerId,centerDepth,adapter:adapter.info};
  raster.dispose();readback.unmap();depthReadback.unmap();device.destroy();return output;
 });
 console.log(JSON.stringify(result,null,2));
 assert.deepEqual(result.shaderErrors,[]);assert.equal(result.validation,null);assert.deepEqual(result.errors,[]);
 assert.equal(result.centerId,1<<16);assert.equal(result.outerId,0);assert.ok(Math.abs(result.centerDepth-.5)<1e-4);
}finally{await browser.close();}
