export * from './common/index.ts';
// Generated by scripts/generate-sdk-facade.ts.
export type { ArrivalPlan } from '../sdk-browser/pageIntegrationHost.ts';
export { autonomousPagesBackend } from '../sdk-browser/autonomousPages.ts';
export type {
  BackendContext,
  BackendDiagnostic,
  BackendFactory,
  DiagnosticDetail,
  RenderBackend,
} from '../sdk-browser/backendTypes.ts';
export type { ComparisonLayout } from '../sdk-browser/comparison.ts';
export type { CpuStepSummary } from '../sdk-browser/cpuProfile.ts';
export { createDiagnosticChannel } from '../sdk-browser/diagnosticChannel.ts';
export type {
  DiagnosticChannel,
  DiagnosticChannelOptions,
  DiagnosticObserver,
} from '../sdk-browser/diagnosticChannel.ts';
export { createExplorer } from '../sdk-browser/explorer.ts';
export type { Explorer } from '../sdk-browser/explorer.ts';
export { createExplorerJob } from '../sdk-browser/index.ts';
export { createGpuPageCache, httpPageSource } from '../sdk-browser/gpuPages.ts';
export { createLightingExperimentBackend } from '../sdk-browser/lightingExperimentBackend.ts';
export { createPageStreamer } from '../sdk-browser/streamingPages.ts';
export type { DecodedGeometryPage } from '../sdk-browser/geometryPage.ts';
export { DEFAULT_BACKENDS } from '../sdk-browser/defaultBackends.ts';
export { detectCapabilities } from '../sdk-browser/capabilities.ts';
export { EngineProfiler } from '../sdk-browser/telemetry.ts';
export { exactPagesBackend } from '../sdk-browser/exactPagesBackend.ts';
export type { ExplorerOptions, PointOfInterest } from '../sdk-browser/explorerOptions.ts';
export type { ExplorerTarget } from '../sdk-browser/explorerTarget.ts';
export { framingFromBounds } from '../sdk-browser/framing.ts';
export type { GeometryPool, PoolClamp, TexturePool } from '../sdk-browser/webgpuMemoryBudgets.ts';
export { gpuPassBlockOf, gpuPassStageOf } from '../sdk-browser/stageMapping.ts';
export type { GpuPassBlock } from '../sdk-browser/stageMapping.ts';
export { gpuPassBlockTotals } from '../sdk-browser/gpuPassBlocks.ts';
export type { GpuPassBlockTotals } from '../sdk-browser/gpuPassBlocks.ts';
export { enginePose, readCameraWorld } from '../sdk-browser/cameraWorld.ts';
export type { HostDrawCamera, HostCamera } from '../sdk-browser/cameraWorld.ts';
export type { HostDrawOutput } from '../sdk-browser/webglRenderTarget.ts';
export type { HostRetentionDelta, StreamPage } from '../sdk-browser/streamingTypes.ts';
export type {
  LightingExperimentRayDiagnostics,
  LightingExperimentRenderState,
} from '../sdk-browser/lightingObservationContracts.ts';
export type { MemoryBudgets, MemoryBudgetsReport } from '../sdk-browser/webgpuPagesMemory.ts';
export type { MultiplyLot } from '../sdk-browser/mathBatchRuntime.ts';
export type { PartitionAudit } from '../sdk-browser/webgpuPartitionAudit.ts';
export { presentationColorDiagnostic } from '../sdk-browser/presentationDiagnostic.ts';
export { referenceBackend } from '../sdk-browser/referenceBackend.ts';
export { replicateInstances } from '../sdk-browser/replicateInstances.ts';
export type { ResidentPage } from '../sdk-browser/gpuPageTypes.ts';
export { runCameraPath } from '../sdk-browser/cameraPath.ts';
export type { ShadowAtlasDigest } from '../sdk-browser/gpuShadowDigest.ts';
export type { SurfaceBuffer, SurfaceCapture } from '../sdk-browser/surfaceBuffer.ts';
export type { TelemetryReport } from '../sdk-browser/telemetryTypes.ts';
export type { TextureLevelReader } from '../sdk-browser/textureLevelReader.ts';
export { threeLodBackend } from '../sdk-browser/threeLod.ts';
export type { TransparentOcclusionAudit } from '../sdk-browser/webgpuTransparentOcclusionAudit.ts';
export { webgpuPagesBackend } from '../sdk-browser/webgpuPages.ts';
export {
  createEngineCamera,
  defaultEngineCamera,
  holdCameraWorld,
  writeEngineCamera,
} from '../sdk-browser/engineCamera.ts';
export type { CameraOptics, EngineCamera } from '../sdk-browser/engineCamera.ts';
export { materialSide, sideOf } from '../sdk-browser/materialSide.ts';
export type { Side } from '../sdk-browser/materialSide.ts';
