export * from './common/index.ts';
// Generated by scripts/generate-sdk-facade.ts.
export { Action, advanceMixers, animation, Mixer } from '../sdk-core/src/world/animation/index.ts';
export type {
  Clip,
  Track,
  TrackBinding,
  TrackKind,
} from '../sdk-core/src/world/animation/index.ts';
export type { ArrivalPlan } from '../sdk-browser/pageIntegrationHost.ts';
export type {
  AtlasLanes,
  LaneCounts,
  TextureCompression,
} from '../sdk-browser/textureBlockFormats.ts';
export type { BackendDiagnostic, DiagnosticDetail } from '../sdk-browser/backendDiagnosticTypes.ts';
export { batch } from '../sdk-browser/world/batch/index.ts';
export type { FloatBatch } from '../sdk-browser/world/batch/index.ts';
export {
  blending,
  colorSpace,
  filter,
  side,
  toneMapping,
  wrap,
} from '../sdk-core/src/world/constants/index.ts';
export type {
  Blending,
  ColorSpace,
  Filter,
  Side,
  ToneMapping,
  Wrap,
} from '../sdk-core/src/world/constants/index.ts';
export { Box3 } from '../sdk-core/src/world/math/box3.ts';
export type { BoundedNode } from '../sdk-core/src/world/math/box3.ts';
export type { BoxTransformLot, MultiplyLot } from '../sdk-browser/mathBatchRuntime.ts';
export { budget } from '../sdk-browser/world/budget/index.ts';
export { buffer, BufferAttribute, InterleavedBuffer } from '../sdk-core/src/world/buffer/index.ts';
export type { BufferNumbers, BufferTypedArray } from '../sdk-core/src/world/buffer/index.ts';
export { camera } from '../sdk-core/src/world/camera/index.ts';
export { Camera } from '../sdk-core/src/world/camera/camera.ts';
export type { CameraParameters, CameraPose } from '../sdk-core/src/world/camera/camera.ts';
export { capability } from '../sdk-browser/world/capability/index.ts';
export { capture } from '../sdk-browser/world/capture/index.ts';
export type { CaptureSize } from '../sdk-browser/world/capture/index.ts';
export type {
  ChangeListener,
  ControlVector,
  PivotCameraControls,
} from '../sdk-browser/cameraControlTypes.ts';
export { Color } from '../sdk-core/src/world/math/color.ts';
export type { ColorInput } from '../sdk-core/src/world/math/color.ts';
export type { ComparisonLayout } from '../sdk-browser/comparison.ts';
export type { CpuStepSummary } from '../sdk-browser/cpuProfile.ts';
export { createDiagnosticChannel } from '../sdk-browser/diagnosticChannel.ts';
export type {
  DiagnosticChannel,
  DiagnosticChannelOptions,
  DiagnosticObserver,
} from '../sdk-browser/diagnosticChannel.ts';
export { createGpuPageCache, httpPageSource } from '../sdk-browser/gpuPages.ts';
export { createPageStreamer } from '../sdk-browser/streamingPages.ts';
export { createWorld } from '../sdk-browser/world/core/world.ts';
export type { World } from '../sdk-browser/world/core/world.ts';
export { Curve, Path, Shape, SplineCurve } from '../sdk-core/src/world/math/curves.ts';
export type { DecodedGeometryPage } from '../sdk-browser/geometryPage.ts';
export { detectCapabilities } from '../sdk-browser/capabilities.ts';
export { diagnostic } from '../sdk-browser/world/diagnostic/index.ts';
export { EngineProfiler } from '../sdk-browser/telemetry.ts';
export { Euler } from '../sdk-core/src/world/math/euler.ts';
export type {
  EulerLike,
  XYLike,
  XYZLike,
  XYZSink,
  XYZWLike,
  XYZWSink,
} from '../sdk-core/src/world/math/likes.ts';
export type { ExtrudeOptions } from '../sdk-core/src/world/geometry/shape.ts';
export type { FirstPersonCameraControls } from '../sdk-browser/cameraFirstPersonControls.ts';
export type { FlyCameraControls } from '../sdk-browser/cameraFlyControls.ts';
export type { FrameInfo, WorldFrameMetrics } from '../sdk-browser/world/core/worldFrames.ts';
export { framingFromBounds } from '../sdk-browser/framing.ts';
export { Frustum, Plane, Ray, Sphere, Triangle } from '../sdk-core/src/world/math/volumes.ts';
export { geometry } from '../sdk-core/src/world/geometry/index.ts';
export { Geometry } from '../sdk-core/src/world/geometry/geometry.ts';
export type { GeometryPool, PoolClamp, TexturePool } from '../sdk-browser/webgpuMemoryBudgets.ts';
export { gpuPassBlockOf, gpuPassStageOf } from '../sdk-browser/stageMapping.ts';
export type { GpuPassBlock } from '../sdk-browser/stageMapping.ts';
export { gpuPassBlockTotals } from '../sdk-browser/gpuPassBlocks.ts';
export type { GpuPassBlockTotals } from '../sdk-browser/gpuPassBlocks.ts';
export { Group, Object3D } from '../sdk-core/src/world/object/object3d.ts';
export type { SceneLink } from '../sdk-core/src/world/object/object3d.ts';
export { helper } from '../sdk-browser/world/helper/index.ts';
export type {
  HostAttribute,
  HostAttributes,
  HostBox,
  HostColour,
  HostDiagnosticFactory,
  HostDiagnosticGeometry,
  HostDiagnosticMaterial,
  HostDisposable,
  HostGeometry,
  HostMaterial,
  HostMaterials,
  HostMesh,
  HostNode,
  HostPoint,
  HostScene,
  HostTexture,
  HostTraversable,
} from '../sdk-browser/hostResources.ts';
export { enginePose, readCameraWorld } from '../sdk-browser/cameraWorld.ts';
export type { HostDrawCamera, HostCamera } from '../sdk-browser/cameraWorld.ts';
export type { HostDrawOutput } from '../sdk-browser/webglRenderTarget.ts';
export type { HostGraphNode, HostRotation, HostVector } from '../sdk-browser/hostGraphNodes.ts';
export type { HostNodeMatrix, MatrixElements } from '../sdk-browser/matrixElements.ts';
export type { HostRetentionDelta, StreamPage } from '../sdk-browser/streamingTypes.ts';
export { light, Light } from '../sdk-core/src/world/light/light.ts';
export type { LightParameters } from '../sdk-core/src/world/light/light.ts';
export { LoadedModel } from '../sdk-browser/world/core/loadedModel.ts';
export type { ModelRecord } from '../sdk-browser/world/core/loadedModel.ts';
export { loader } from '../sdk-browser/world/loader/index.ts';
export { Scene } from '../sdk-browser/world/core/scene.ts';
export type { LoadOptions } from '../sdk-browser/world/core/scene.ts';
export { material } from '../sdk-core/src/world/material/index.ts';
export { Material } from '../sdk-core/src/world/material/material.ts';
export type { MaterialParameters } from '../sdk-core/src/world/material/material.ts';
export { math } from '../sdk-core/src/world/math/index.ts';
export { Matrix3, Matrix4 } from '../sdk-core/src/world/math/matrix4.ts';
export type { MemoryBudgets, MemoryBudgetsReport } from '../sdk-browser/webgpuPagesMemory.ts';
export { Mesh } from '../sdk-core/src/world/object/mesh.ts';
export type { Primitive } from '../sdk-core/src/world/object/mesh.ts';
export { metric } from '../sdk-browser/world/metric/index.ts';
export { object } from '../sdk-core/src/world/object/index.ts';
export { page } from '../sdk-browser/world/page/index.ts';
export type { PageStreamer, WorldPageSource } from '../sdk-browser/world/page/index.ts';
export type { PanZoomCameraControls } from '../sdk-browser/cameraPanZoomControls.ts';
export type { PartitionAudit } from '../sdk-browser/webgpuPartitionAudit.ts';
export { texture } from '../sdk-browser/world/texture/index.ts';
export type { PixelImage } from '../sdk-browser/world/texture/index.ts';
export type { PlacementRows } from '../sdk-browser/placement/placementRows.ts';
export type { PointOfInterest } from '../sdk-browser/explorerOptions.ts';
export { pose } from '../sdk-browser/world/pose/index.ts';
export type { PosedWorld } from '../sdk-browser/world/pose/index.ts';
export { presentationColorDiagnostic } from '../sdk-browser/presentationDiagnostic.ts';
export { probeWorldRenderer } from '../sdk-browser/world/capability/worldReady.ts';
export type { WorldRenderer } from '../sdk-browser/world/capability/worldReady.ts';
export { Quaternion } from '../sdk-core/src/world/math/quaternion.ts';
export type { ResidentPage } from '../sdk-browser/gpuPageTypes.ts';
export type { ShadowAtlasDigest } from '../sdk-browser/gpuShadowDigest.ts';
export { Spherical, Vector2, Vector4 } from '../sdk-core/src/world/math/vector2.ts';
export type { SurfaceBuffer, SurfaceCapture } from '../sdk-browser/surfaceBuffer.ts';
export type { TelemetryReport } from '../sdk-browser/telemetryTypes.ts';
export { Texture } from '../sdk-core/src/world/texture/texture.ts';
export type {
  TextureLevel,
  TextureLevelReader,
  TextureLevelRequest,
} from '../sdk-browser/textureLevelReader.ts';
export type { TrackballCameraControls } from '../sdk-browser/cameraTrackballControls.ts';
export type { TransparentOcclusionAudit } from '../sdk-browser/webgpuTransparentOcclusionAudit.ts';
export { Vector3 } from '../sdk-core/src/world/math/vector3.ts';
export type { Vec3Input } from '../sdk-core/src/world/math/vector3.ts';
export type { WorldControls } from '../sdk-browser/world/core/worldCamera.ts';
export type { WorldOptions } from '../sdk-browser/world/core/worldOptions.ts';
export type { WorldTarget } from '../sdk-browser/world/core/worldTarget.ts';
export {
  createEngineCamera,
  defaultEngineCamera,
  holdCameraWorld,
  writeEngineCamera,
} from '../sdk-browser/engineCamera.ts';
export type { CameraOptics, EngineCamera, OrthographicBox } from '../sdk-browser/engineCamera.ts';
export { materialSide, sideOf } from '../sdk-browser/materialSide.ts';
