export * from './common/index.ts';
// Generated by scripts/generate-sdk-facade.ts.
export { Action, advanceMixers, animation, Mixer } from '../sdk-core/src/world/animation/index.ts';
export type {
  Clip,
  Track,
  TrackBinding,
  TrackKind,
} from '../sdk-core/src/world/animation/index.ts';
export type { ArrivalPlan } from '../sdk-browser/src/page/integration/host.ts';
export type {
  AtlasLanes,
  LaneCounts,
  TextureCompression,
} from '../sdk-browser/src/texture/blockFormats.ts';
export type { BackendDiagnostic, DiagnosticDetail } from '../sdk-browser/src/diagnostic/types.ts';
export { batch } from '../sdk-browser/src/world/batch/index.ts';
export type { FloatBatch } from '../sdk-browser/src/world/batch/index.ts';
export type {
  BeforeFrameInfo,
  FrameInfo,
  WorldFrameMetrics,
} from '../sdk-browser/src/world/core/worldFrames.ts';
export {
  blending,
  colorSpace,
  filter,
  side,
  toneMapping,
  wrap,
} from '../sdk-core/src/world/constants/index.ts';
export type {
  Blending,
  ColorSpace,
  Filter,
  Side,
  ToneMapping,
  Wrap,
} from '../sdk-core/src/world/constants/index.ts';
export { Box3 } from '../sdk-core/src/world/math/box3.ts';
export type { BoundedNode } from '../sdk-core/src/world/math/box3.ts';
export type { BoxTransformLot, MultiplyLot } from '../sdk-browser/src/math/batchRuntime.ts';
export { budget } from '../sdk-browser/src/world/budget/index.ts';
export { buffer, BufferAttribute, InterleavedBuffer } from '../sdk-core/src/world/buffer/index.ts';
export type { BufferNumbers, BufferTypedArray } from '../sdk-core/src/world/buffer/index.ts';
export { camera } from '../sdk-core/src/world/camera/index.ts';
export { Camera } from '../sdk-core/src/world/camera/camera.ts';
export type { CameraParameters, CameraPose } from '../sdk-core/src/world/camera/camera.ts';
export { capability } from '../sdk-browser/src/world/capability/index.ts';
export type { Capsule, CapsuleContact, CapsulePush } from '../sdk-core/src/collision/capsule.ts';
export { capture } from '../sdk-browser/src/world/capture/index.ts';
export type { CaptureSize } from '../sdk-browser/src/world/capture/index.ts';
export type {
  ChangeListener,
  ControlVector,
  PivotCameraControls,
} from '../sdk-browser/src/camera/controls/types.ts';
export type { CharacterCameraControls } from '../sdk-browser/src/camera/controls/characterControls.ts';
export type {
  CharacterCollision,
  TriangleCollision,
} from '../sdk-core/src/collision/characterCollision.ts';
export { Color } from '../sdk-core/src/world/math/color.ts';
export type { ColorInput } from '../sdk-core/src/world/math/color.ts';
export type { ComparisonLayout } from '../sdk-browser/src/measurement/comparison.ts';
export type { CpuStepSummary } from '../sdk-browser/src/stage/cpuProfile.ts';
export { createDiagnosticChannel } from '../sdk-browser/src/diagnostic/channel.ts';
export type {
  DiagnosticChannel,
  DiagnosticChannelOptions,
  DiagnosticObserver,
} from '../sdk-browser/src/diagnostic/channel.ts';
export { createGpuPageCache, httpPageSource } from '../sdk-browser/src/gpu/page/pages.ts';
export { createPageStreamer } from '../sdk-browser/src/streaming/pages.ts';
export { createWorld } from '../sdk-browser/src/world/core/world.ts';
export type { World } from '../sdk-browser/src/world/core/world.ts';
export { Curve, Path, Shape, SplineCurve } from '../sdk-core/src/world/math/curves.ts';
export type { DecodedGeometryPage } from '../sdk-browser/src/page/decode/geometryPage.ts';
export { detectCapabilities } from '../sdk-browser/src/measurement/capabilities.ts';
export { diagnostic } from '../sdk-browser/src/world/diagnostic/index.ts';
export { EngineProfiler } from '../sdk-browser/src/diagnostic/telemetry.ts';
export { Euler } from '../sdk-core/src/world/math/euler.ts';
export type {
  EulerLike,
  XYLike,
  XYZLike,
  XYZSink,
  XYZWLike,
  XYZWSink,
} from '../sdk-core/src/world/math/likes.ts';
export type { ExtrudeOptions } from '../sdk-core/src/world/geometry/shape.ts';
export type { FirstPersonCameraControls } from '../sdk-browser/src/camera/controls/firstPersonControls.ts';
export type { FlyCameraControls } from '../sdk-browser/src/camera/controls/flyControls.ts';
export { framingFromBounds } from '../sdk-browser/src/camera/framing.ts';
export { Frustum, Plane, Ray, Sphere, Triangle } from '../sdk-core/src/world/math/volumes.ts';
export { geometry } from '../sdk-core/src/world/geometry/index.ts';
export { Geometry } from '../sdk-core/src/world/geometry/geometry.ts';
export type {
  GeometryPool,
  PoolClamp,
  TexturePool,
} from '../sdk-browser/src/webgpu/residency/memoryBudgets.ts';
export { gpuPassBlockOf, gpuPassStageOf } from '../sdk-browser/src/stage/mapping.ts';
export type { GpuPassBlock } from '../sdk-browser/src/stage/mapping.ts';
export { gpuPassBlockTotals } from '../sdk-browser/src/gpu/core/passBlocks.ts';
export type { GpuPassBlockTotals } from '../sdk-browser/src/gpu/core/passBlocks.ts';
export { Group, Object3D } from '../sdk-core/src/world/object/object3d.ts';
export type { SceneLink } from '../sdk-core/src/world/object/object3d.ts';
export type { HeadSettings, PersonHead } from '../sdk-browser/src/camera/controls/look.ts';
export { helper } from '../sdk-browser/src/world/helper/index.ts';
export type {
  HostAttribute,
  HostAttributes,
  HostBox,
  HostColour,
  HostDiagnosticFactory,
  HostDiagnosticGeometry,
  HostDiagnosticMaterial,
  HostDisposable,
  HostGeometry,
  HostMaterial,
  HostMaterials,
  HostMesh,
  HostNode,
  HostPoint,
  HostScene,
  HostTexture,
  HostTraversable,
} from '../sdk-browser/src/host/resources.ts';
export { enginePose, readCameraWorld } from '../sdk-browser/src/camera/world.ts';
export type { HostDrawCamera, HostCamera } from '../sdk-browser/src/camera/world.ts';
export type { HostDrawOutput } from '../sdk-browser/src/webgl/core/renderTarget.ts';
export type {
  HostGraphNode,
  HostRotation,
  HostVector,
} from '../sdk-browser/src/host/scene/graphNodes.ts';
export type { HostNodeMatrix, MatrixElements } from '../sdk-browser/src/math/matrixElements.ts';
export type { HostRetentionDelta, StreamPage } from '../sdk-browser/src/streaming/types.ts';
export { light, Light } from '../sdk-core/src/world/light/light.ts';
export type { LightParameters } from '../sdk-core/src/world/light/light.ts';
export { LoadedModel } from '../sdk-browser/src/world/core/loadedModel.ts';
export type { ModelRecord } from '../sdk-browser/src/world/core/loadedModel.ts';
export { loader } from '../sdk-browser/src/world/loader/index.ts';
export { Scene } from '../sdk-browser/src/world/core/scene.ts';
export type { LoadOptions } from '../sdk-browser/src/world/core/scene.ts';
export { material } from '../sdk-core/src/world/material/index.ts';
export { Material } from '../sdk-core/src/world/material/material.ts';
export type { MaterialParameters } from '../sdk-core/src/world/material/material.ts';
export { math } from '../sdk-core/src/world/math/index.ts';
export { Matrix3, Matrix4 } from '../sdk-core/src/world/math/matrix4.ts';
export type {
  MemoryBudgets,
  MemoryBudgetsReport,
} from '../sdk-browser/src/webgpu/pages/io/memory.ts';
export { Mesh } from '../sdk-core/src/world/object/mesh.ts';
export type { Primitive } from '../sdk-core/src/world/object/mesh.ts';
export { metric } from '../sdk-browser/src/world/metric/index.ts';
export { object } from '../sdk-core/src/world/object/index.ts';
export type { OrbitCameraControls } from '../sdk-browser/src/camera/controls/orbitControls.ts';
export { page } from '../sdk-browser/src/world/page/index.ts';
export type { PageStreamer, WorldPageSource } from '../sdk-browser/src/world/page/index.ts';
export type { PanZoomCameraControls } from '../sdk-browser/src/camera/controls/panZoomControls.ts';
export type { PartitionAudit } from '../sdk-browser/src/webgpu/core/partitionAudit.ts';
export { texture } from '../sdk-browser/src/world/texture/index.ts';
export type { PixelImage } from '../sdk-browser/src/world/texture/index.ts';
export type { PlacementRows } from '../sdk-browser/src/placement/rows.ts';
export type { PointOfInterest } from '../sdk-browser/src/world/session/options.ts';
export { pose } from '../sdk-browser/src/world/pose/index.ts';
export type { PosedWorld } from '../sdk-browser/src/world/pose/index.ts';
export { presentationColorDiagnostic } from '../sdk-browser/src/diagnostic/presentationDiagnostic.ts';
export { probeWorldRenderer } from '../sdk-browser/src/world/capability/worldReady.ts';
export type { WorldRenderer } from '../sdk-browser/src/world/capability/worldReady.ts';
export { Quaternion } from '../sdk-core/src/world/math/quaternion.ts';
export type { ResidentPage } from '../sdk-browser/src/gpu/page/types.ts';
export type { ShadowAtlasDigest } from '../sdk-browser/src/gpu/shadow/digest.ts';
export { Spherical, Vector2, Vector4 } from '../sdk-core/src/world/math/vector2.ts';
export type { SurfaceBuffer, SurfaceCapture } from '../sdk-browser/src/scene/surfaceBuffer.ts';
export type { TelemetryReport } from '../sdk-browser/src/diagnostic/telemetryTypes.ts';
export { Texture } from '../sdk-core/src/world/texture/texture.ts';
export type {
  TextureLevel,
  TextureLevelReader,
  TextureLevelRequest,
} from '../sdk-browser/src/texture/levelReader.ts';
export type { TrackballCameraControls } from '../sdk-browser/src/camera/controls/trackballControls.ts';
export type { TransparentOcclusionAudit } from '../sdk-browser/src/webgpu/transparent/occlusionAudit.ts';
export { Vector3 } from '../sdk-core/src/world/math/vector3.ts';
export type { Vec3Input } from '../sdk-core/src/world/math/vector3.ts';
export type { WorldControls } from '../sdk-browser/src/world/core/worldCamera.ts';
export type { WorldOptions } from '../sdk-browser/src/world/core/worldOptions.ts';
export type { WorldTarget } from '../sdk-browser/src/world/core/worldTarget.ts';
export {
  createEngineCamera,
  defaultEngineCamera,
  holdCameraWorld,
  writeEngineCamera,
} from '../sdk-browser/src/camera/engineCamera.ts';
export type {
  CameraOptics,
  EngineCamera,
  OrthographicBox,
} from '../sdk-browser/src/camera/engineCamera.ts';
export { materialSide, sideOf } from '../sdk-browser/src/scene/materialSide.ts';
