use super::*;
pub(in crate::tests) mod autonomous_scene;
pub(in crate::tests) mod cuts;
pub(in crate::tests) mod extension_tables;
mod material_variants;
pub(in crate::tests) mod mesh_pages;
pub(in crate::tests) mod motion_tables;
pub(in crate::tests) mod partition;
pub(in crate::tests) mod partition_pages;
pub(in crate::tests) mod partition_rows;
pub(in crate::tests) mod scene_tables;
pub(in crate::tests) mod surface_tables;
pub(in crate::tests) mod visibility;
pub(in crate::tests) mod world_roots;
