/**
 * Build this repository's engine as one self-contained bundle: a host imports only this
 * repository's own module. The engine names no rendering library (issue #275), and the build
 * proves it on its own product: a runtime file that folds in a module of one is refused.
 */
import { build } from 'esbuild';
import { copyFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';

export async function buildRuntime(root: string, outdir: string) {
  await mkdir(outdir, { recursive: true });
  const { metafile } = await build({
    absWorkingDir: root,
    metafile: true,
    entryPoints: {
      engine: 'packages/sdk-browser/src/index.ts',
      pageDecodeWorker: 'packages/sdk-browser/src/page/decode/pageDecodeWorker.ts',
      pageIntegrationWorker: 'packages/sdk-browser/src/page/integration/pageIntegrationWorker.ts',
      // The physics worker, spawned only by a world that turns physics on.
      physicsWorker: 'packages/sdk-browser/src/physics/physicsWorker.ts',
      // The examples' own panels, imported beside the engine; they touch nothing of it.
      kit: 'site/examples/kit/index.ts',
    },
    outdir,
    bundle: true,
    minify: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    supported: { 'template-literal': false },
    banner: {
      js: '// Generated by pnpm build:docs. Self-contained: no dependency is external.',
    },
    logLevel: 'warning',
  });
  const folded = Object.entries(metafile.outputs).flatMap(([output, { inputs }]) =>
    Object.keys(inputs)
      .filter((input) => /(?:^|\/)node_modules\/three\//.test(input))
      .map((input) => `${output} <- ${input}`),
  );
  if (folded.length)
    throw new Error(`the runtime folds in a rendering library:\n${folded.join('\n')}`);
  for (const wasm of [
    'page/decode/pageCodec.wasm',
    'physics/joltPhysics.wasm',
    'physics/joltPhysicsThreads.wasm',
  ])
    await copyFile(
      resolve(root, 'packages/sdk-browser/src', wasm),
      resolve(outdir, wasm.slice(wasm.lastIndexOf('/') + 1)),
    );
}
