/**
 * Build this repository's engine as one self-contained bundle: no page of the site declares or
 * loads a third-party engine dependency of its own, so this build folds it into `engine.js` and a
 * host imports only this repository's own module.
 */
import { build } from 'esbuild';
import { copyFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';

export async function buildRuntime(root: string, outdir: string) {
  await mkdir(outdir, { recursive: true });
  await build({
    absWorkingDir: root,
    entryPoints: {
      engine: 'packages/sdk-browser/src/index.ts',
      pageDecodeWorker: 'packages/sdk-browser/src/page/decode/pageDecodeWorker.ts',
      pageIntegrationWorker: 'packages/sdk-browser/src/page/integration/pageIntegrationWorker.ts',
      // The examples' own panels, imported beside the engine; they touch nothing of it.
      kit: 'site/examples/kit/index.ts',
      // The open world's play layer, and the worker that runs its physics.
      openworld: 'site/examples/kit/openworld/index.ts',
      openworldSim: 'site/examples/kit/openworld/play/sim.worker.ts',
    },
    outdir,
    bundle: true,
    minify: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    supported: { 'template-literal': false },
    banner: {
      js: '// Generated by pnpm build:docs. Self-contained: no third-party engine dependency is external.',
    },
    logLevel: 'warning',
  });
  await copyFile(
    resolve(root, 'packages/sdk-browser/src/page/decode/pageCodec.wasm'),
    resolve(outdir, 'pageCodec.wasm'),
  );
  // Jolt as its package ships it: the module finds its WebAssembly beside itself. The open
  // world's worker imports it on demand, so no other page pays for it.
  const jolt = resolve(root, 'node_modules/jolt-physics/dist');
  for (const file of ['jolt-physics.wasm.js', 'jolt-physics.wasm.wasm'])
    await copyFile(resolve(jolt, file), resolve(outdir, file));
}
