// Bundles the public surface the documentation runs — the common facade's maths, diagnostic,
// quality and format tables, and the internal browser depth convention — into one browser
// module, `js/engine.js` of the built site, so every demo of the portal and every snippet run in
// the code editor executes the engine itself rather than a copy of it. The entry is the module the
// demos import, `site/demos/engine.ts`: one list of exports, typed for the demos, bundled for the
// editor.
import { build } from 'esbuild';

const BANNER = `// Generated by pnpm build:docs from packages/ — do not edit.`;

/** Writes the browser ESM bundle of `site/demos/engine.ts` to `outfile`. */
export async function buildDemo(root: string, outfile: string) {
  await build({
    absWorkingDir: root,
    entryPoints: ['site/demos/engine.ts'],
    outfile,
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    banner: { js: BANNER },
    logLevel: 'warning',
  });
}
