import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {
  HOST_BLENDING_ADDITIVE,
  HOST_BLENDING_MULTIPLY,
  HOST_BLENDING_NONE,
  HOST_BLENDING_NORMAL,
  HOST_BLENDING_SUBTRACTIVE,
  HOST_COLOUR_SPACE_LINEAR,
  HOST_COLOUR_SPACE_NONE,
  HOST_COLOUR_SPACE_SRGB,
  HOST_DEPTH_LESS_EQUAL,
  HOST_FILTER_LINEAR,
  HOST_FILTER_LINEAR_MIP_LINEAR,
  HOST_FILTER_LINEAR_MIP_NEAREST,
  HOST_FILTER_NEAREST,
  HOST_FILTER_NEAREST_MIP_LINEAR,
  HOST_FILTER_NEAREST_MIP_NEAREST,
  HOST_FORMAT_RED,
  HOST_FORMAT_RGB,
  HOST_FORMAT_RGBA,
  HOST_MAPPING_UV,
  HOST_NORMAL_MAP_TANGENT_SPACE,
  HOST_WRAP_CLAMP_TO_EDGE,
  HOST_WRAP_MIRRORED_REPEAT,
  HOST_WRAP_REPEAT,
} from './surfaceConstants.ts';

// The engine path no longer names the host library to compare a sampler state or a blend
// equation; this test does, so that the names above stay the host's own numbers.
test('the engine names the host surface constants by the values the host declares', () => {
  assert.deepEqual(
    [
      HOST_WRAP_REPEAT,
      HOST_WRAP_CLAMP_TO_EDGE,
      HOST_WRAP_MIRRORED_REPEAT,
      HOST_FILTER_NEAREST,
      HOST_FILTER_NEAREST_MIP_NEAREST,
      HOST_FILTER_NEAREST_MIP_LINEAR,
      HOST_FILTER_LINEAR,
      HOST_FILTER_LINEAR_MIP_NEAREST,
      HOST_FILTER_LINEAR_MIP_LINEAR,
      HOST_MAPPING_UV,
      HOST_BLENDING_NONE,
      HOST_BLENDING_NORMAL,
      HOST_BLENDING_ADDITIVE,
      HOST_BLENDING_SUBTRACTIVE,
      HOST_BLENDING_MULTIPLY,
      HOST_NORMAL_MAP_TANGENT_SPACE,
      HOST_DEPTH_LESS_EQUAL,
      HOST_FORMAT_RGBA,
      HOST_FORMAT_RGB,
      HOST_FORMAT_RED,
      HOST_COLOUR_SPACE_SRGB,
      HOST_COLOUR_SPACE_LINEAR,
      HOST_COLOUR_SPACE_NONE,
    ],
    [
      THREE.RepeatWrapping,
      THREE.ClampToEdgeWrapping,
      THREE.MirroredRepeatWrapping,
      THREE.NearestFilter,
      THREE.NearestMipmapNearestFilter,
      THREE.NearestMipmapLinearFilter,
      THREE.LinearFilter,
      THREE.LinearMipmapNearestFilter,
      THREE.LinearMipmapLinearFilter,
      THREE.UVMapping,
      THREE.NoBlending,
      THREE.NormalBlending,
      THREE.AdditiveBlending,
      THREE.SubtractiveBlending,
      THREE.MultiplyBlending,
      THREE.TangentSpaceNormalMap,
      THREE.LessEqualDepth,
      THREE.RGBAFormat,
      THREE.RGBFormat,
      THREE.RedFormat,
      THREE.SRGBColorSpace,
      THREE.LinearSRGBColorSpace,
      THREE.NoColorSpace,
    ],
  );
});
