import { WRAP_COORD_WGSL } from '../../visibility/wrapModes.ts'
import { PAGE_FILTER_SHIFT } from './pageTable.ts'
import { SAMPLE_WRAP_SHIFT } from '../../texture/sampling.ts'
import { SAMPLING_WGSL } from './samplingWgsl.ts'
import { type WgslDecl, wgslBlock } from '../../../../math/src/wgsl/decl.ts'
import { bilinear4 } from '../../../../math/src/wgsl/sampling.ts'

/**
 * Atlas reads, generated by name: the `${k}Pages` buffer and the `${k}Pool*` textures cannot be
 * passed as WGSL arguments, so each atlas has its own functions, from the same text, on the
 * textures of `pool` (`tilePoolWgsl`).
 */
export const tileKindWgsl = (k: string, pool: WgslDecl) =>
  wgslBlock(
    `tileKindWgsl(${k})`,
    [pool, SAMPLING_WGSL, WRAP_COORD_WGSL, bilinear4],
    `fn ${k}Slot(slot:u32)->TileSlot{
 let h=PAGE_HEADER+slot*PAGE_SLOT;
 let last=${k}Pages[h+2u];let tail=${k}Pages[h+3u];let word=last>>${PAGE_FILTER_SHIFT}u;
 return TileSlot(sizeOf(${k}Pages[h]),${k}Pages[h+1u],last&0xffu,${k}Pages[3]+slot*PAGE_LEVELS,tail&0xffffffu,tail>>24u,word&${(1 << SAMPLE_WRAP_SHIFT) - 1}u,word>>${SAMPLE_WRAP_SHIFT}u);
}
/** The tap read in the pool of the texture's lane: lossless (0), RGBA blocks (1), or two
 *  channels with Y in the second channel (2) or in the alpha (3). */
fn ${k}Tap(tap:u32,t:TileTap)->vec4f{
 if(tap==0u){return textureSampleLevel(${k}Pool0,mapsSampler,t.uv,t.layer,0.0);}
 if(tap>=2u){
  let v=textureSampleLevel(${k}Pool2,mapsSampler,t.uv,t.layer,0.0);
  let xy=vec2f(v.x,select(v.y,v.w,tap==3u));
  return vec4f(xy,rebuiltZ(xy),1.0);
 }
 return textureSampleLevel(${k}Pool1,mapsSampler,t.uv,t.layer,0.0);
}
/** Table word that holds the tile of a texel at a streamed level. */
fn ${k}Entry(s:TileSlot,uv:vec2f,level:u32)->u32{
 let lsize=levelSize(s.size,level);
 return ${k}Pages[s.levels+level]+tileEntry(levelTexel(uv,lsize),lsize);
}
/** Where to read a texel whose word is known: the tile it names, or the tail at the requested level. */
fn ${k}Place(s:TileSlot,uv:vec2f,level:u32,word:u32,nearest:bool)->TileTap{
 if(word==0u){
  let res=max(level,s.tail);
  let rtexel=pickTexel(levelTexel(uv,levelSize(s.size,res)),nearest);
  let origin=placeOrigin(s.tailWord)+vec2f(tailOffset(res-s.tail),0.0);
  return poolTap(origin,rtexel,placeLayer(s.tailWord));
 }
 let res=(word>>24u)&0x7fu;
 let rtexel=pickTexel(levelTexel(uv,levelSize(s.size,res)),nearest);
 let local=rtexel-floor(rtexel/TEXEL_TILE)*TEXEL_TILE;
 return poolTap(placeOrigin(word),local,placeLayer(word));
}
fn ${k}Fetch(s:TileSlot,uv:vec2f,level:u32,finest:bool,nearest:bool)->vec4f{
 var word=0u;
 if(level<s.tail){
  word=${k}Pages[${k}Entry(s,uv,level)];
  if(finest&&word==0u){word=${k}Pages[${k}Entry(s,uv,0u)];}
 }
 return ${k}Tap(s.tap,${k}Place(s,uv,level,word,nearest));
}
/** One level of a read, the coordinate brought back by the texture's addressing nibble: a single
 *  fetch off a seam; on the seam of a repeating period — half a texel of THIS level from either
 *  edge, wider the coarser the level —, the four fetches the sampler's rule mixes, the last texel
 *  and the first, by their weights at this level. A nearest read takes the texel the fold named. */
fn ${k}Level(s:TileSlot,uv:vec2f,level:u32,finest:bool,nearest:bool)->vec4f{
 if(!wrapRepete(s.wrap)){return ${k}Fetch(s,wrapReplie(uv,s.wrap),level,finest,nearest);}
 let t=wrapUv(uv,s.wrap,levelSize(s.size,level));
 if(!t.couture||nearest){return ${k}Fetch(s,t.proche,level,finest,nearest);}
 let s00=${k}Fetch(s,t.proche,level,finest,nearest);
 let s10=${k}Fetch(s,vec2f(t.loin.x,t.proche.y),level,finest,nearest);
 let s01=${k}Fetch(s,vec2f(t.proche.x,t.loin.y),level,finest,nearest);
 let s11=${k}Fetch(s,t.loin,level,finest,nearest);
 return bilinear4(s00,s10,s01,s11,t.poids);
}
/** Filtered read: the two levels the footprint straddles, mixed by their share. */
fn ${k}Blend(s:TileSlot,uv:vec2f,lod:f32,nearest:bool,finest:bool)->vec4f{
 let l0=floor(lod);let t=lod-l0;
 let a=${k}Level(s,uv,u32(l0),finest,nearest);
 if(t<=0.0||l0>=f32(s.last)){return a;}
 return mix(a,${k}Level(s,uv,u32(l0)+1u,finest,nearest),t);
}
fn ${k}SampleAt(s:TileSlot,uv:vec2f,lod:f32,nearest:bool)->vec4f{return ${k}Blend(s,uv,lod,nearest,false);}`,
  )
