// Generated by scripts/generate-sdk-facade.ts.
export type { ArrivalPlan } from '../../sdk-browser/src/page/integration/host.ts';
export type {
  AtlasLanes,
  LaneCounts,
  TextureCompression,
} from '../../sdk-browser/src/texture/blockFormats.ts';
export type {
  BackendDiagnostic,
  DiagnosticDetail,
} from '../../sdk-browser/src/diagnostic/types.ts';
export type { BoxTransformLot, MultiplyLot } from '../../sdk-browser/src/math/batchRuntime.ts';
export type { Capsule, CapsuleContact, CapsulePush } from '../../sdk-core/src/collision/capsule.ts';
export type {
  ChangeListener,
  ControlVector,
  PivotCameraControls,
} from '../../sdk-browser/src/camera/controls/types.ts';
export type { CharacterCameraControls } from '../../sdk-browser/src/camera/controls/characterControls.ts';
export type {
  CharacterCollision,
  TriangleCollision,
} from '../../sdk-core/src/collision/characterCollision.ts';
export type { ComparisonLayout } from '../../sdk-browser/src/measurement/comparison.ts';
export { ObjectPhysics } from '../../sdk-core/src/physics/objectPhysics.ts';
export type {
  ContactEvent,
  ContactEventName,
  PhysicsHost,
} from '../../sdk-core/src/physics/objectPhysics.ts';
export type { CpuStepSummary } from '../../sdk-browser/src/stage/cpuProfile.ts';
export { createDiagnosticChannel } from '../../sdk-browser/src/diagnostic/channel.ts';
export type {
  DiagnosticChannel,
  DiagnosticChannelOptions,
  DiagnosticObserver,
} from '../../sdk-browser/src/diagnostic/channel.ts';
export { createGpuPageCache, httpPageSource } from '../../sdk-browser/src/gpu/page/pages.ts';
export { createPageStreamer } from '../../sdk-browser/src/streaming/pages.ts';
export type { DecodedGeometryPage } from '../../sdk-browser/src/page/decode/geometryPage.ts';
export {
  DEFAULT_PHYSICS_BUDGET,
  GRAVITY_PRESETS,
  PHYSICS_MATERIALS,
} from '../../sdk-core/src/physics/options.ts';
export type {
  GravityPreset,
  PhysicsBodyOptions,
  PhysicsBudget,
  PhysicsMaterialPreset,
  PhysicsMatter,
  PhysicsOption,
  PhysicsPart,
  PhysicsPrimitive,
  PhysicsShape,
  PhysicsType,
} from '../../sdk-core/src/physics/options.ts';
export { detectCapabilities } from '../../sdk-browser/src/measurement/capabilities.ts';
export { EngineProfiler } from '../../sdk-browser/src/diagnostic/telemetry.ts';
export type { FirstPersonCameraControls } from '../../sdk-browser/src/camera/controls/firstPersonControls.ts';
export type { FlyCameraControls } from '../../sdk-browser/src/camera/controls/flyControls.ts';
export { framingFromBounds } from '../../sdk-browser/src/camera/framing.ts';
export type {
  GeometryPool,
  MemoryBudgets,
  MemoryBudgetsReport,
  PoolClamp,
} from '../../sdk-browser/src/residency/pools.ts';
export { gpuPassBlockOf, gpuPassStageOf } from '../../sdk-browser/src/stage/mapping.ts';
export type { GpuPassBlock } from '../../sdk-browser/src/stage/mapping.ts';
export { gpuPassBlockTotals } from '../../sdk-browser/src/gpu/core/passBlocks.ts';
export type { GpuPassBlockTotals } from '../../sdk-browser/src/gpu/core/passBlocks.ts';
export { GraphAngles, GraphRotation } from '../../sdk-browser/src/host/graph/rotation.ts';
export {
  GraphAttribute,
  GraphInterleavedAttribute,
  GraphInterleavedBuffer,
} from '../../sdk-browser/src/host/graph/attributes.ts';
export type { GraphArray, GraphElements } from '../../sdk-browser/src/host/graph/attributes.ts';
export { GraphGeometry } from '../../sdk-browser/src/host/graph/geometry.ts';
export { GraphMesh } from '../../sdk-browser/src/host/graph/mesh.ts';
export { GraphNode } from '../../sdk-browser/src/host/graph/node.ts';
export type { GraphNodeKind } from '../../sdk-browser/src/host/graph/nodeKind.ts';
export { GraphSurface } from '../../sdk-browser/src/host/graph/surface.ts';
export { GraphTexture } from '../../sdk-browser/src/host/graph/texture.ts';
export { GraphVector } from '../../sdk-browser/src/host/graph/vector.ts';
export type {
  GravityInput,
  WorldPhysics,
  WorldPhysicsOptions,
} from '../../sdk-browser/src/physics/worldPhysics.ts';
export type { HeadSettings, PersonHead } from '../../sdk-browser/src/camera/controls/look.ts';
export type {
  HostAttribute,
  HostAttributes,
  HostBox,
  HostColour,
  HostDiagnosticFactory,
  HostDiagnosticGeometry,
  HostDiagnosticMaterial,
  HostDisposable,
  HostGeometry,
  HostMaterial,
  HostMaterials,
  HostMesh,
  HostNode,
  HostPoint,
  HostScene,
  HostTexture,
  HostTraversable,
} from '../../sdk-browser/src/host/resources.ts';
export { enginePose, readCameraWorld } from '../../sdk-browser/src/camera/world.ts';
export type { HostDrawCamera, HostCamera } from '../../sdk-browser/src/camera/world.ts';
export type { HostDrawOutput } from '../../sdk-browser/src/webgl/core/renderTarget.ts';
export type {
  HostGraphNode,
  HostRotation,
  HostVector,
} from '../../sdk-browser/src/host/scene/graphNodes.ts';
export type { HostNodeMatrix, MatrixElements } from '../../sdk-browser/src/math/matrixElements.ts';
export type { HostRetentionDelta, StreamPage } from '../../sdk-browser/src/streaming/types.ts';
export { joint, Joint } from '../../sdk-core/src/physics/joint.ts';
export type {
  JointKind,
  JointLimits,
  JointMotor,
  JointOptions,
} from '../../sdk-core/src/physics/joint.ts';
export type { OrbitCameraControls } from '../../sdk-browser/src/camera/controls/orbitControls.ts';
export type { PanZoomCameraControls } from '../../sdk-browser/src/camera/controls/panZoomControls.ts';
export type { PartitionAudit } from '../../sdk-browser/src/webgpu/core/partitionAudit.ts';
export type { PhysicsStats } from '../../sdk-browser/src/physics/protocol.ts';
export type { PlacementRows } from '../../sdk-browser/src/placement/rows.ts';
export { presentationColorDiagnostic } from '../../sdk-browser/src/diagnostic/presentationDiagnostic.ts';
export type { ResidentPage } from '../../sdk-browser/src/gpu/page/types.ts';
export type { ShadowAtlasDigest } from '../../sdk-browser/src/gpu/shadow/digest.ts';
export type { SurfaceBuffer, SurfaceCapture } from '../../sdk-browser/src/scene/surfaceBuffer.ts';
export type { TelemetryReport } from '../../sdk-browser/src/diagnostic/telemetryTypes.ts';
export type {
  TextureLevel,
  TextureLevelReader,
  TextureLevelRequest,
} from '../../sdk-browser/src/texture/levelReader.ts';
export type { TexturePool } from '../../sdk-browser/src/webgpu/residency/memoryBudgets.ts';
export type { TrackballCameraControls } from '../../sdk-browser/src/camera/controls/trackballControls.ts';
export type { TransparentOcclusionAudit } from '../../sdk-browser/src/webgpu/transparent/occlusionAudit.ts';
export type { TriangleTree } from '../../sdk-core/src/collision/triangleTree.ts';
export type { VehicleDriver, VehicleInput } from '../../sdk-core/src/physics/vehicle.ts';
export type { WaterSpec } from '../../sdk-core/src/fluids/buoyancy.ts';
export type { WaveSpec } from '../../sdk-core/src/fluids/waves.ts';
export {
  createEngineCamera,
  defaultEngineCamera,
  holdCameraWorld,
  writeEngineCamera,
} from '../../sdk-browser/src/camera/engineCamera.ts';
export type {
  CameraOptics,
  EngineCamera,
  OrthographicBox,
} from '../../sdk-browser/src/camera/engineCamera.ts';
export { materialSide, sideOf } from '../../sdk-browser/src/scene/materialSide.ts';
