// Generated by scripts/generate-sdk-facade.ts.
export {
  Action,
  advanceMixers,
  animation,
  Mixer,
} from '../../sdk-core/src/world/animation/index.ts';
export type {
  Clip,
  Track,
  TrackBinding,
  TrackKind,
} from '../../sdk-core/src/world/animation/index.ts';
export { batch } from '../../sdk-browser/src/world/batch/index.ts';
export type { FloatBatch } from '../../sdk-browser/src/world/batch/index.ts';
export type {
  BeforeFrameInfo,
  FrameInfo,
  WorldFrameMetrics,
} from '../../sdk-browser/src/world/core/worldFrames.ts';
export {
  blending,
  colorSpace,
  filter,
  side,
  toneMapping,
  wrap,
} from '../../sdk-core/src/world/constants/index.ts';
export type {
  Blending,
  ColorSpace,
  Filter,
  Side,
  ToneMapping,
  Wrap,
} from '../../sdk-core/src/world/constants/index.ts';
export { Box3 } from '../../sdk-core/src/world/math/box3.ts';
export type { BoundedNode } from '../../sdk-core/src/world/math/box3.ts';
export { budget } from '../../sdk-browser/src/world/budget/index.ts';
export { buffer } from '../../sdk-core/src/world/buffer/index.ts';
export type { BufferNumbers } from '../../sdk-core/src/world/buffer/index.ts';
export {
  BufferAttribute,
  InterleavedBuffer,
  InterleavedBufferAttribute,
} from '../../sdk-core/src/world/buffer/attribute.ts';
export type { VertexAttribute } from '../../sdk-core/src/world/buffer/attribute.ts';
export { VertexElements } from '../../sdk-core/src/world/buffer/elements.ts';
export type { BufferTypedArray } from '../../sdk-core/src/world/buffer/elements.ts';
export { camera } from '../../sdk-core/src/world/camera/index.ts';
export { Camera } from '../../sdk-core/src/world/camera/camera.ts';
export type { CameraParameters, CameraPose } from '../../sdk-core/src/world/camera/camera.ts';
export type { CanvasPoint, RaycastOptions } from '../../sdk-browser/src/world/core/worldRaycast.ts';
export { capability } from '../../sdk-browser/src/world/capability/index.ts';
export { capture } from '../../sdk-browser/src/world/capture/index.ts';
export type { CaptureSize } from '../../sdk-browser/src/world/capture/index.ts';
export { Color } from '../../sdk-core/src/world/math/color.ts';
export type { ColorInput } from '../../sdk-core/src/world/math/color.ts';
export { controls } from '../../sdk-browser/src/world/controls/index.ts';
export { createWorld } from '../../sdk-browser/src/world/core/world.ts';
export type { World } from '../../sdk-browser/src/world/core/world.ts';
export { Curve, Path, Shape, SplineCurve } from '../../sdk-core/src/world/math/curves.ts';
export { diagnostic } from '../../sdk-browser/src/world/diagnostic/index.ts';
export { Euler } from '../../sdk-core/src/world/math/euler.ts';
export type {
  EulerLike,
  XYLike,
  XYZLike,
  XYZSink,
  XYZWLike,
  XYZWSink,
} from '../../sdk-core/src/world/math/likes.ts';
export type { ExtrudeOptions } from '../../sdk-core/src/world/geometry/shape.ts';
export type { Fog } from '../../sdk-browser/src/world/core/sceneFog.ts';
export { Frustum, Plane, Ray, Sphere, Triangle } from '../../sdk-core/src/world/math/volumes.ts';
export { geometry } from '../../sdk-core/src/world/geometry/index.ts';
export { Geometry } from '../../sdk-core/src/world/geometry/geometry.ts';
export { Group, Object3D } from '../../sdk-core/src/world/object/object3d.ts';
export { helper } from '../../sdk-browser/src/world/helper/index.ts';
export { raycast } from '../../sdk-core/src/world/object/raycast.ts';
export type { Intersection } from '../../sdk-core/src/world/object/raycast.ts';
export { light, Light } from '../../sdk-core/src/world/light/light.ts';
export type { LightParameters } from '../../sdk-core/src/world/light/light.ts';
export { LoadedModel } from '../../sdk-browser/src/world/core/loadedModel.ts';
export type { ModelRecord } from '../../sdk-browser/src/world/core/loadedModel.ts';
export { loader } from '../../sdk-browser/src/world/loader/index.ts';
export { Scene } from '../../sdk-browser/src/world/core/scene.ts';
export type { LoadOptions } from '../../sdk-browser/src/world/core/scene.ts';
export { material } from '../../sdk-core/src/world/material/index.ts';
export { Material } from '../../sdk-core/src/world/material/material.ts';
export type { MaterialParameters } from '../../sdk-core/src/world/material/material.ts';
export { math } from '../../sdk-core/src/world/math/index.ts';
export { Matrix3, Matrix4 } from '../../sdk-core/src/world/math/matrix4.ts';
export { Mesh } from '../../sdk-core/src/world/object/mesh.ts';
export type { Primitive } from '../../sdk-core/src/world/object/mesh.ts';
export { metric } from '../../sdk-browser/src/world/metric/index.ts';
export { object } from '../../sdk-core/src/world/object/index.ts';
export { page } from '../../sdk-browser/src/world/page/index.ts';
export type { PageStreamer, WorldPageSource } from '../../sdk-browser/src/world/page/index.ts';
export { texture } from '../../sdk-browser/src/world/texture/index.ts';
export type { PixelImage } from '../../sdk-browser/src/world/texture/index.ts';
export type { PointOfInterest } from '../../sdk-browser/src/world/session/options.ts';
export { pose } from '../../sdk-browser/src/world/pose/index.ts';
export type { PosedWorld } from '../../sdk-browser/src/world/pose/index.ts';
export { probeWorldRenderer } from '../../sdk-browser/src/world/capability/worldReady.ts';
export type { WorldRenderer } from '../../sdk-browser/src/world/capability/worldReady.ts';
export { Quaternion } from '../../sdk-core/src/world/math/quaternion.ts';
export type {
  SavedCamera,
  SavedGeometry,
  SavedMaterial,
  SavedNode,
  SavedScene,
} from '../../sdk-browser/src/world/saved/format.ts';
export type { SceneLink } from '../../sdk-core/src/world/object/sceneLink.ts';
export { Spherical, Vector2, Vector4 } from '../../sdk-core/src/world/math/vector2.ts';
export { Texture } from '../../sdk-core/src/world/texture/texture.ts';
export type {
  TransformControls,
  TransformControlsOptions,
  TransformEvent,
  TransformHost,
} from '../../sdk-browser/src/world/controls/transform.ts';
export type {
  TransformHandle,
  TransformMode,
  TransformSnap,
  TransformSpace,
} from '../../sdk-browser/src/world/controls/transformMath.ts';
export { TransformNode } from '../../sdk-core/src/world/object/transformNode.ts';
export { Vector3 } from '../../sdk-core/src/world/math/vector3.ts';
export type { Vec3Input } from '../../sdk-core/src/world/math/vector3.ts';
export type { WorldControls } from '../../sdk-browser/src/world/core/worldCamera.ts';
export type { WorldOptions } from '../../sdk-browser/src/world/core/worldOptions.ts';
export type { WorldTarget } from '../../sdk-browser/src/world/core/worldTarget.ts';
