// Generated by scripts/generate-sdk-facade.ts.
export { adaptivePixelError, LOD_QUALITY, lodQuality } from '../../sdk-core/src/lod/policy.ts';
export type { LodQualityId } from '../../sdk-core/src/lod/policy.ts';
export {
  addHemisphereIrradiance,
  addIrradianceCoefficients,
  addUniformIrradiance,
  emptyIrradiance,
  environmentLights,
  SCENE_ENVIRONMENT_FLOATS,
  TONE_MAPPING_RANK,
} from '../../sdk-core/src/scene/core/environment.ts';
export type {
  SceneEnvironment,
  SceneToneMapping,
} from '../../sdk-core/src/scene/core/environment.ts';
export type {
  AlphaMode,
  LinearRgb,
  Material,
  Side,
} from '../../sdk-core/src/contracts/material.ts';
export { assertSceneProxy, decodeSceneProxy } from '../../sdk-core/src/scene/core/proxy.ts';
export {
  biasedDepthBits,
  DEPTH_LAYER_BIAS_UNITS,
  depthLayerUnits,
  MAX_DEPTH_LAYER,
} from '../../sdk-core/src/lod/depthLayer.ts';
export {
  clusterErrorAtDepth,
  clusterErrorPixels,
  screenErrorBound,
} from '../../sdk-core/src/lod/screenErrorBound.ts';
export { createSceneRoot, SceneRoot } from '../../sdk-core/src/scene/core/root.ts';
export type {
  DagReport,
  DagStall,
  DagStallCause,
  DagStallSummary,
  DagWarning,
} from '../../sdk-core/src/contracts/dag.ts';
export { dagWarningsDiagnostic } from '../../sdk-core/src/contracts/dagWarnings.ts';
export type {
  PrimitiveDagStall,
  PrimitiveDagWarning,
} from '../../sdk-core/src/contracts/dagWarnings.ts';
export type {
  GeometryPageDescriptor,
  GeometryPageFormat,
  PrimitiveQuantization,
} from '../../sdk-core/src/page/contracts.ts';
export type { GpuMemoryFrameMetrics } from '../../sdk-core/src/contracts/gpuMemory.ts';
export type { OcclusionFrameMetrics } from '../../sdk-core/src/contracts/occlusionMetrics.ts';
export {
  referenceScreenError,
  screenErrorVariant,
  setScreenErrorVariant,
} from '../../sdk-core/src/lod/screenErrorVariant.ts';
export type { ScreenErrorVariant } from '../../sdk-core/src/lod/screenErrorVariant.ts';
export { SCENE_MODEL_VERSION } from '../../sdk-core/src/scene/core/nodeContracts.ts';
export type { SceneNodeOptions, SceneState } from '../../sdk-core/src/scene/core/nodeContracts.ts';
export { SceneNode } from '../../sdk-core/src/scene/core/node.ts';
export type { ShadowFrameMetrics } from '../../sdk-core/src/contracts/shadowMetrics.ts';
export {
  TABLE_FLAGS,
  TABLE_NUMBERS,
  TABLE_SLOTS,
  TABLE_TRIPLETS,
} from '../../sdk-core/src/scene/core/tableSurfaces.ts';
export type {
  TableMaterial,
  TableTexture,
  TableTextureSlot,
} from '../../sdk-core/src/scene/core/tableSurfaces.ts';
