// Generated by scripts/generate-sdk-facade.ts.
export { adaptivePixelError, LOD_QUALITY, lodQuality } from '../../sdk-core/lodPolicy.ts';
export type { LodQualityId } from '../../sdk-core/lodPolicy.ts';
export {
  addHemisphereIrradiance,
  addIrradianceCoefficients,
  addUniformIrradiance,
  emptyIrradiance,
  environmentLights,
  SCENE_ENVIRONMENT_FLOATS,
  TONE_MAPPING_RANK,
} from '../../sdk-core/sceneEnvironment.ts';
export type { SceneEnvironment, SceneToneMapping } from '../../sdk-core/sceneEnvironment.ts';
export type { AlphaMode, LinearRgb, Material, Side } from '../../sdk-core/materialContract.ts';
export { assertSceneProxy, decodeSceneProxy } from '../../sdk-core/sceneProxy.ts';
export {
  assertSceneTables,
  MATERIAL_TABLE_VERSION,
  NODE_TABLE_VERSION,
  SCENE_TABLES_FILE,
  SCENE_TABLES_VERSION,
  TABLE_FLAGS,
  TABLE_NUMBERS,
  TABLE_SLOTS,
  TABLE_TRIPLETS,
} from '../../sdk-core/sceneTableContracts.ts';
export type {
  PreparedSceneTables,
  TableMaterial,
  TableNode,
  TableTexture,
  TableTextureSlot,
} from '../../sdk-core/sceneTableContracts.ts';
export {
  biasedDepthBits,
  DEPTH_LAYER_BIAS_UNITS,
  depthLayerUnits,
  MAX_DEPTH_LAYER,
} from '../../sdk-core/depthLayer.ts';
export { createSceneRoot, SceneRoot } from '../../sdk-core/sceneRoot.ts';
export type { DagReport, DagWarning } from '../../sdk-core/dagContracts.ts';
export { dagWarningsDiagnostic } from '../../sdk-core/dagWarnings.ts';
export type { PrimitiveDagWarning } from '../../sdk-core/dagWarnings.ts';
export type {
  GeometryPageDescriptor,
  GeometryPageFormat,
  PrimitiveQuantization,
} from '../../sdk-core/geometryPageContracts.ts';
export type { GpuMemoryFrameMetrics } from '../../sdk-core/gpuMemoryContracts.ts';
export type { OcclusionFrameMetrics } from '../../sdk-core/occlusionMetricsContracts.ts';
export {
  referenceScreenError,
  screenErrorVariant,
  setScreenErrorVariant,
} from '../../sdk-core/screenErrorVariant.ts';
export type { ScreenErrorVariant } from '../../sdk-core/screenErrorVariant.ts';
export { SCENE_MODEL_VERSION } from '../../sdk-core/sceneNodeContracts.ts';
export type { SceneNodeOptions, SceneState } from '../../sdk-core/sceneNodeContracts.ts';
export { SceneNode } from '../../sdk-core/sceneNode.ts';
export type { ShadowFrameMetrics } from '../../sdk-core/shadowMetricsContracts.ts';
