// Generated by scripts/generate-sdk-facade.mjs.
export {
  BOUNCE_PROBES_PER_FRAME,
  BOUNCE_SETTINGS,
  PROBE_FLOATS,
} from '../../sdk-core/bounceContracts.ts';
export { bounceBatchOf, createBounceBudget } from '../../sdk-core/bounceBudget.ts';
export type { BounceBudget } from '../../sdk-core/bounceBudget.ts';
export { createBounceCascades } from '../../sdk-core/bounceCascades.ts';
export type { BounceCascadeLevel, BounceCascades } from '../../sdk-core/bounceCascades.ts';
export { createBounceOccupancy } from '../../sdk-core/bounceOccupancy.ts';
export type { BounceOccupancy } from '../../sdk-core/bounceOccupancy.ts';
export { createDefaultLightingSceneLights } from '../../sdk-core/lightingSceneControls.ts';
export { createLightingScene } from '../../sdk-core/lightingExperimentScene.ts';
export { createSceneLightStore, LIGHT_FIELD } from '../../sdk-core/sceneLightStore.ts';
export type { SceneLightStore } from '../../sdk-core/sceneLightStore.ts';
export { createShadowPlan } from '../../sdk-core/sceneLightShadowPlan.ts';
export type { ShadowPlan } from '../../sdk-core/sceneLightShadowPlan.ts';
export { createTransport } from '../../sdk-core/lightingTransport.ts';
export { desiredFaceSide, SHADOW_FACE_SIDES } from '../../sdk-core/sceneLightShadowAtlas.ts';
export { exportLightingGltf } from '../../sdk-core/lightingSceneGltf.ts';
export {
  faceCountOf,
  POINT_FACE_AXES,
  SHADOW_CULL_FLOATS,
  SHADOW_FACE_FLOATS,
  SHADOW_SLICE_FLOATS,
  writeFace,
} from '../../sdk-core/sceneLightShadowFaces.ts';
export {
  LIGHT_KIND,
  LIGHT_SETTINGS,
  MAX_SHADOW_SLICES,
  POINT_FACES,
  SCENE_LIGHT_BUFFER_FLOATS,
  SCENE_LIGHT_FLOATS,
  SCENE_LIGHT_HEADER_FLOATS,
  SCENE_LIGHT_VERSION,
} from '../../sdk-core/sceneLightContracts.ts';
export type {
  SceneEnvironment,
  SceneLight,
  SceneLightingView,
  ShadowViewpoint,
} from '../../sdk-core/sceneLightContracts.ts';
export type { LightingCapabilities } from '../../sdk-core/sceneLightCapabilities.ts';
export type {
  LightingSceneLight,
  Patch,
  Scene,
  Surface,
  Vec3,
} from '../../sdk-core/lightingSceneTypes.ts';
export { pageRowsOf, SHADOW_PAGE } from '../../sdk-core/sceneLightShadowPages.ts';
export {
  PROXY_CHILD_WORDS,
  PROXY_CHILDREN,
  PROXY_NODE_FLOATS,
  PROXY_NODE_WORDS,
  PROXY_TRIANGLE_FLOATS,
  SCENE_PROXY_HEADER_WORDS,
  SCENE_PROXY_MAGIC,
  SCENE_PROXY_VERSION,
} from '../../sdk-core/proxyContracts.ts';
export type {
  SceneProxy,
  SceneProxyColumns,
  SceneProxyDescriptor,
} from '../../sdk-core/proxyContracts.ts';
export { RECTS_PER_SLICE } from '../../sdk-core/sceneLightShadowSlices.ts';
export { regionRect } from '../../sdk-core/sceneLightShadowVolume.ts';
export { solveTransportOracle } from '../../sdk-core/lightingTransportOracle.ts';
export type {
  TransportOptions,
  TransportProgress,
  TransportResult,
  TransportSnapshot,
} from '../../sdk-core/lightingTransportContracts.ts';
export { validateSceneEnvironment, validateSceneLight } from '../../sdk-core/sceneLightValidate.ts';
