// Generated by scripts/generate-sdk-facade.ts.
export {
  addScaledVector3,
  applyMatrix3Vector3,
  copyScaledVector3,
  crossVector3,
  dotVector3,
  lengthSqVector3,
  normalizeVector3,
  scaleVector3,
  transformAffinePoint,
  transformDirectionVector3,
  transformHomogeneousPoint,
} from '../../math/src/vector/vector.ts'
export {
  addTransformNode,
  createTransformTree,
  NODE_AUTO_UPDATE,
  setNodeAutoUpdate,
  setNodeLocalMatrix,
  setNodePosition,
  setNodeQuaternion,
  setNodeScale,
} from '../../sdk-core/src/world/transform-tree/transformTree.ts'
export type { TransformTree } from '../../sdk-core/src/world/transform-tree/transformTree.ts'
export {
  alignDown,
  alignUp,
  bitWords,
  ceilDiv,
  floorLog2,
  isPow2,
  nextPow2,
  workgroupCount,
} from '../../math/src/scalar/integers.ts'
export {
  axisAngleQuaternion,
  multiplyQuaternion,
  normalizeQuaternion,
  rotateByQuaternion,
} from '../../math/src/quaternion/quaternion.ts'
export {
  basisMatrix4,
  decomposeMatrix4,
  uniformScaleMatrix4,
} from '../../math/src/matrix/matrix4Trs.ts'
export {
  BOX_VALUES,
  boxCornersInto,
  boxEmpty,
  boxExpandByPoint,
  boxIsEmpty,
  boxTransform,
  boxUnion,
} from '../../math/src/geometry/box.ts'
export {
  boxConeRejects,
  CONE_LENGTH_RATIO,
  CONE_LENGTH_RATIO_WGSL,
  CONE_ORTHO_EPS,
  CONE_ORTHO_EPS_WGSL,
  HALF_PI_WGSL,
} from '../../math/src/geometry/cone.ts'
export {
  boxTransformBatch,
  boxTransformUnionBatch,
  boxUnionBatch,
  HIERARCHY_ROOT,
  hierarchyUpdateBatch,
  multiplyMatrix4Batch,
} from '../../math/src/batch/batch.ts'
export {
  createCameraFrame,
  orthographicProjection,
  perspectiveProjection,
  updateCameraFrame,
} from '../../math/src/projection/camera.ts'
export type { CameraFrame } from '../../math/src/projection/camera.ts'
export { clamp, lerp, saturate, wrap } from '../../math/src/scalar/reals.ts'
export {
  clipPlanesFromMatrix,
  FRUSTUM_PLANE_VALUES,
  frustumFarPlane,
  frustumPlanesFromMatrix,
} from '../../math/src/geometry/frustum/frustum.ts'
export { composeMatrix4, composeMatrix4Batch } from '../../math/src/matrix/matrix4Compose.ts'
export { coneRejects, maxStretch } from '../../math/src/projection/projectionOracles.ts'
export {
  copyMatrix4,
  determinantMatrix4,
  IDENTITY_MATRIX4,
  linearPartDeterminant,
  multiplyMatrix4,
} from '../../math/src/matrix/matrix4.ts'
export type { NumberSink } from '../../math/src/matrix/matrix4.ts'
export {
  createPathGovernor,
  PATH_EXPLORE_EVERY,
  PATH_MIN_SAMPLES,
  PATH_SWITCH_RUNS,
} from '../../sdk-core/src/runtime/path/governor.ts'
export type { PathGovernor } from '../../sdk-core/src/runtime/path/governor.ts'
export {
  decomposeMatrix4Batch,
  invertMatrix4Batch,
  normalMatrix3Batch,
} from '../../math/src/batch/transforms.ts'
export {
  DEG2RAD,
  FLOAT32_MAX,
  FLOAT32_STEP,
  GOLDEN_FRACTION,
  GOLDEN_RATIO,
  HALF_PI,
  MIB,
  RAD2DEG,
  TAU,
} from '../../math/src/constants.ts'
export { frustumClipBox, frustumExcludesBox } from '../../math/src/geometry/frustum/box.ts'
export { frustumKeepsBoxBatch, sphereFromBoundsBatch } from '../../math/src/batch/culling.ts'
export {
  HIZ_NOTHING,
  hizBuildFlat,
  hizFlatLayout,
  hizFlatLevels,
} from '../../sdk-core/src/hiz/pyramidFlat.ts'
export type { HizFlat } from '../../sdk-core/src/hiz/pyramidFlat.ts'
export { hslToLinearRgb, linearToSrgb, srgbToLinear } from '../../math/src/color/color.ts'
export { invertMatrix4 } from '../../math/src/matrix/matrix4Inverse.ts'
export {
  linearPartScale,
  SINGULAR_DETERMINANT_WGSL,
  SINGULAR_DETERMINANT,
  adjugateFactor,
  normalizedLinearDeterminant,
} from '../../math/src/matrix/singular.ts'
export { linearToSrgbBatch, srgbToLinearBatch } from '../../math/src/batch/color.ts'
export { lookAtNode } from '../../sdk-core/src/world/transform-tree/lookAt.ts'
export {
  markNodeWorldNeedsUpdate,
  updateNodeMatrixWorld,
  updateNodeWorldMatrix,
} from '../../sdk-core/src/world/transform-tree/update.ts'
export { MATH_PATH_CONTRACT } from '../../sdk-core/src/runtime/path/contracts.ts'
export type {
  MathPath,
  MathPathMetrics,
  MathPathMode,
  MathPathOperation,
} from '../../sdk-core/src/runtime/path/contracts.ts'
export {
  MATRIX_VALUES,
  NORMAL_MATRIX_VALUES,
  POSITION_VALUES,
  QUATERNION_VALUES,
  SPHERE_VALUES,
} from '../../math/src/batch/strides.ts'
export {
  matrixAtRenderOrigin,
  viewToRenderOrigin,
  worldToRenderOrigin,
} from '../../math/src/projection/renderOrigin.ts'
export { matrixWindingCw } from '../../math/src/matrix/orientation.ts'
export {
  nodeWorldDirection,
  nodeWorldPosition,
  nodeWorldQuaternion,
} from '../../sdk-core/src/world/transform-tree/read.ts'
export { normalMatrix3 } from '../../math/src/matrix/matrix3.ts'
export { quantile } from '../../math/src/scalar/quantile.ts'
export {
  removeTransformNode,
  reparentTransformNode,
} from '../../sdk-core/src/world/transform-tree/structure.ts'
export { sphereFromBounds } from '../../math/src/geometry/sphere.ts'
export {
  transformDirectionsBatch,
  transformPointsBatch,
  transformPointsByMatricesBatch,
} from '../../math/src/batch/points.ts'
