// Generated by scripts/generate-sdk-facade.ts.
export {
  addScaledVector3,
  applyMatrix3Vector3,
  copyScaledVector3,
  crossVector3,
  dotVector3,
  lengthSqVector3,
  normalizeVector3,
  scaleVector3,
  transformAffinePoint,
  transformDirectionVector3,
  transformHomogeneousPoint,
} from '../../sdk-core/mathVector.ts';
export {
  addTransformNode,
  createTransformTree,
  NODE_AUTO_UPDATE,
  setNodeAutoUpdate,
  setNodeLocalMatrix,
  setNodePosition,
  setNodeQuaternion,
  setNodeScale,
} from '../../sdk-core/mathTransformTree.ts';
export type { TransformTree } from '../../sdk-core/mathTransformTree.ts';
export {
  axisAngleQuaternion,
  multiplyQuaternion,
  normalizeQuaternion,
  rotateByQuaternion,
} from '../../sdk-core/mathQuaternion.ts';
export {
  basisMatrix4,
  decomposeMatrix4,
  uniformScaleMatrix4,
} from '../../sdk-core/mathMatrix4Trs.ts';
export {
  BOX_VALUES,
  boxCornersInto,
  boxEmpty,
  boxExpandByPoint,
  boxIsEmpty,
  boxTransform,
  boxUnion,
} from '../../sdk-core/mathBox.ts';
export {
  boxConeRejects,
  CONE_LENGTH_RATIO,
  CONE_LENGTH_RATIO_WGSL,
  CONE_ORTHO_EPS,
  CONE_ORTHO_EPS_WGSL,
  HALF_PI,
  HALF_PI_WGSL,
} from '../../sdk-core/mathCone.ts';
export {
  boxTransformBatch,
  boxTransformUnionBatch,
  boxUnionBatch,
  HIERARCHY_ROOT,
  hierarchyUpdateBatch,
  multiplyMatrix4Batch,
} from '../../sdk-core/mathBatch.ts';
export {
  createCameraFrame,
  orthographicProjection,
  perspectiveProjection,
  updateCameraFrame,
} from '../../sdk-core/mathCamera.ts';
export type { CameraFrame } from '../../sdk-core/mathCamera.ts';
export {
  clipPlanesFromMatrix,
  FRUSTUM_PLANE_VALUES,
  frustumFarPlane,
  frustumPlanesFromMatrix,
  frustumPlanesToLocal,
} from '../../sdk-core/mathFrustum.ts';
export { coneRejects, dot, maxStretch } from '../../sdk-core/projectionOracles.ts';
export {
  clusterErrorAtDepth,
  clusterErrorPixels,
  screenErrorBound,
} from '../../sdk-core/screenErrorBound.ts';
export { composeMatrix4, composeMatrix4Batch } from '../../sdk-core/mathMatrix4Compose.ts';
export {
  copyMatrix4,
  determinantMatrix4,
  IDENTITY_MATRIX4,
  linearPartDeterminant,
  multiplyMatrix4,
} from '../../sdk-core/mathMatrix4.ts';
export type { NumberSink } from '../../sdk-core/mathMatrix4.ts';
export {
  createPathGovernor,
  PATH_EXPLORE_EVERY,
  PATH_MIN_SAMPLES,
  PATH_SWITCH_RUNS,
} from '../../sdk-core/mathPathGovernor.ts';
export type { PathGovernor } from '../../sdk-core/mathPathGovernor.ts';
export {
  decomposeMatrix4Batch,
  invertMatrix4Batch,
  normalMatrix3Batch,
} from '../../sdk-core/mathBatchTransforms.ts';
export { frustumClipBox, frustumExcludesBox } from '../../sdk-core/mathFrustumBox.ts';
export { frustumKeepsBoxBatch, sphereFromBoundsBatch } from '../../sdk-core/mathBatchCulling.ts';
export {
  HIZ_NOTHING,
  hizBuildPyramid,
  hizFootprintFar,
  hizOccluded,
  hizReduceCeil,
} from '../../sdk-core/hizOracles.ts';
export {
  hizBuildFlat,
  hizFlatLayout,
  hizFlatLevels,
  hizFootprintFarFlat,
} from '../../sdk-core/hizPyramidFlat.ts';
export type { HizFlat } from '../../sdk-core/hizPyramidFlat.ts';
export { hslToLinearRgb, linearToSrgb, srgbToLinear } from '../../sdk-core/mathColor.ts';
export { invertMatrix4 } from '../../sdk-core/mathMatrix4Inverse.ts';
export {
  linearPartScale,
  SINGULAR_DETERMINANT_WGSL,
  SINGULAR_DETERMINANT,
  adjugateFactor,
  normalizedLinearDeterminant,
} from '../../sdk-core/mathSingular.ts';
export { linearToSrgbBatch, srgbToLinearBatch } from '../../sdk-core/mathBatchColor.ts';
export { lookAtNode } from '../../sdk-core/mathTransformTreeLookAt.ts';
export {
  markNodeWorldNeedsUpdate,
  updateNodeMatrixWorld,
  updateNodeWorldMatrix,
} from '../../sdk-core/mathTransformTreeUpdate.ts';
export { MATH_PATH_CONTRACT } from '../../sdk-core/mathPathContracts.ts';
export type {
  MathPath,
  MathPathMetrics,
  MathPathMode,
  MathPathOperation,
} from '../../sdk-core/mathPathContracts.ts';
export {
  MATRIX_VALUES,
  NORMAL_MATRIX_VALUES,
  POSITION_VALUES,
  QUATERNION_VALUES,
  SPHERE_VALUES,
} from '../../sdk-core/mathBatchStrides.ts';
export {
  matrixAtRenderOrigin,
  viewToRenderOrigin,
  worldToRenderOrigin,
} from '../../sdk-core/mathRenderOrigin.ts';
export { matrixWindingCw } from '../../sdk-core/matrixOrientation.ts';
export {
  nodeWorldDirection,
  nodeWorldMirrorsFaces,
  nodeWorldPosition,
  nodeWorldQuaternion,
  nodeWorldScale,
} from '../../sdk-core/mathTransformTreeRead.ts';
export { normalMatrix3 } from '../../sdk-core/mathMatrix3.ts';
export {
  removeTransformNode,
  reparentTransformNode,
} from '../../sdk-core/mathTransformTreeStructure.ts';
export { sphereFromBounds } from '../../sdk-core/mathSphere.ts';
export {
  transformDirectionsBatch,
  transformPointsBatch,
  transformPointsByMatricesBatch,
} from '../../sdk-core/mathBatchPoints.ts';
