// Generated by scripts/generate-sdk-facade.ts.
export {
  assertCacheIdentity,
  assertCachePointer,
  assertCacheReady,
  assertFormat,
  EngineError,
} from '../../sdk-core/cacheContracts.ts';
export type { PageSource } from '../../sdk-core/cacheContracts.ts';
export { assertManifestBinary, isBinaryManifest } from '../../sdk-core/manifestBinaryTypes.ts';
export type {
  ManifestBinaryDescriptor,
  SlimClusterManifest,
  SlimCulling,
  SlimPrimitive,
  SlimPrimitiveBinary,
  SlimStreams,
  SlimStructure,
} from '../../sdk-core/manifestBinaryTypes.ts';
export {
  blocksAcross,
  levelBlockBytes,
  PREVIEW_BASE,
  PREVIEW_MAX_LEVELS,
  previewBlockBytes,
  previewFirstLevel,
  previewIsWhole,
  previewLastLevel,
  previewLevelCount,
  previewLevelSize,
  previewPixelBytes,
} from '../../sdk-core/texturePreviewLevels.ts';
export {
  clusterSphereValid,
  pageCarriesClusterError,
  primitiveIsDrawable,
  primitiveUsesClusterErrors,
  UNSPLIT_PASS,
} from '../../sdk-core/geometryContracts.ts';
export type {
  ClusterGroup,
  ClusterManifest,
  ClusterStructure,
  CullingHierarchy,
  Page,
  Primitive,
  StreamBundle,
  StreamCatalogue,
} from '../../sdk-core/geometryContracts.ts';
export { manifestBinaryRanges } from '../../sdk-core/manifestBinaryLayout.ts';
export type { Counts } from '../../sdk-core/manifestBinaryLayout.ts';
export {
  createPageIntegrationPlan,
  planPageIntegration,
  sortPages,
} from '../../sdk-core/pageIntegrationPlan.ts';
export type { PageIntegrationPlan } from '../../sdk-core/pageIntegrationPlan.ts';
export {
  decodeManifestBinary,
  decodeManifestPreviews,
} from '../../sdk-core/manifestBinaryDecode.ts';
export { encodeManifestBinary } from '../../sdk-core/manifestBinaryEncode.ts';
export {
  GEOMETRY_PAGE_CODEC,
  GEOMETRY_PAGE_FORMAT_VERSION,
  MANIFEST_BINARY_MAGIC,
  MANIFEST_BINARY_VERSION,
  COLUMN_KIND,
} from '../../sdk-core/manifestBinaryFormat.ts';
export type { ColumnKind } from '../../sdk-core/manifestBinaryFormat.ts';
export {
  PAGE_DECODE_FAILURES,
  PAGE_DECODE_PROTOCOL,
  pageDecodeFailureCode,
  pageDecodeWorkerCount,
} from '../../sdk-core/pageDecodeContracts.ts';
export type {
  PageDecodeAnswer,
  PageDecodeCancel,
  PageDecodeDone,
  PageDecodeFailed,
  PageDecodeFailureCode,
  PageDecodeGeometryPayload,
  PageDecodeOp,
  PageDecodeRequest,
  PageDecodeShare,
} from '../../sdk-core/pageDecodeContracts.ts';
export {
  PAGE_INTEGRATION_FAILURES,
  PAGE_INTEGRATION_PROTOCOL,
  PAGE_SLICE_STRIDE,
  PAGE_SPEC_STRIDE,
  SLICE_OFFSET_WORDS,
  SLICE_PAGE_INDEX,
  SLICE_WORDS,
  SPEC_PAGE_INDEX,
  SPEC_STREAM_OFFSET,
  SPEC_TRIANGLES,
} from '../../sdk-core/pageIntegrationContracts.ts';
export type {
  PageIntegrationAnswer,
  PageIntegrationDone,
  PageIntegrationFailed,
  PageIntegrationFailureCode,
  PageIntegrationRequest,
} from '../../sdk-core/pageIntegrationContracts.ts';
export {
  PREVIEW_ATLAS_COLOR,
  PREVIEW_ATLAS_DATA,
  PREVIEW_ATLAS_NAMES,
  PREVIEW_BLOCK_BYTES,
  PREVIEW_BLOCK_FORMATS,
  PREVIEW_BLOCK_SIDE,
  PREVIEW_LAYOUT_NAMES,
  PREVIEW_LOSSLESS_FORMAT,
  TEXTURE_PREVIEW_VERSION,
} from '../../sdk-core/texturePreviewFormat.ts';
export type { TextureBlockFormat, TextureLayout } from '../../sdk-core/texturePreviewFormat.ts';
export type { TextureFrameMetrics } from '../../sdk-core/textureMetricsContracts.ts';
export { textureLevelFormat, textureLevelUrl } from '../../sdk-core/textureLevelUrl.ts';
export type { TextureLevelFormat } from '../../sdk-core/textureLevelUrl.ts';
export type { TexturePreview } from '../../sdk-core/texturePreviewContracts.ts';
