import type { PageModel } from './pageModel.ts';

/** Each formula's WGSL parameters, then its return type. */
export const SIGNATURES: Record<keyof PageModel<string>, string[]> = {
  shadowRing: ['v:i32', 'n:i32', 'i32'],
  shadowRingPageEntry: ['pages:i32', 'x:i32', 'y:i32', 'i32'],
  shadowFacePageEntry: ['pages:i32', 'x:i32', 'y:i32', 'i32'],
  shadowSunLevelEntry: ['level:i32', 'i32'],
  shadowLampMapEntry: ['face:i32', 'mip:i32', 'i32'],
  shadowLampEntryMip: ['rest:i32', 'i32'],
  shadowLampMipPages: ['mip:i32', 'i32'],
  shadowLampEntryLocal: ['rest:i32', 'i32'],
  shadowFacePageX: ['pages:i32', 'local:i32', 'i32'],
  shadowFacePageY: ['pages:i32', 'local:i32', 'i32'],
  shadowLampView: ['face:i32', 'mip:i32', 'i32'],
  shadowSunSlotLevel: ['slot:i32', 'finest:i32', 'i32'],
  shadowRingPage: ['r:i32', 'origin:i32', 'pages:i32', 'i32'],
  shadowWindowHolds: ['v:i32', 'first:i32', 'count:i32', 'i32'],
  shadowSunCoarseness: ['level:i32', 'finest:i32', 'i32'],
  shadowLampCoarseness: ['mip:i32', 'i32'],
  shadowSunLevelOf: ['footprint:f32', 'i32'],
  shadowSunReadLevel: ['footprint:f32', 'finest:i32', 'i32'],
  shadowSunTexelMetres: ['level:i32', 'f32'],
  shadowSunMapTexel: ['u:f32', 'origin:i32', 'level:i32', 'f32'],
  shadowPageOfTexel: ['t:f32', 'i32'],
  shadowLampFinestTexel: ['tanHalf:f32', 'radius:f32', 'f32'],
  shadowLampReadMip: ['footprint:f32', 'texel0:f32', 'i32'],
  shadowLampMapTexel: ['ndc:f32', 'side:f32', 'f32'],
  shadowPcfEdge: ['t:f32', 'first:f32', 'i32'],
  shadowRegionLow: ['pages:f32', 'x:f32', 'f32'],
  shadowRegionHigh: ['pages:f32', 'x:f32', 'f32'],
  shadowCropScale: ['low:f32', 'high:f32', 'f32'],
  shadowCropOffset: ['low:f32', 'high:f32', 'f32'],
  shadowSunSquareCentre: ['x:f32', 'cells:f32', 'metres:f32', 'f32'],
  shadowAtlasClip: ['origin:f32', 'size:f32', 'f32'],
  shadowPcfStep: ['t:f32', 'first:f32', 'i32'],
  shadowCropped: ['x:f32', 'w:f32', 'scale:f32', 'offset:f32', 'f32'],
  shadowOrthoScale: ['h:f32', 'f32'],
  shadowOrthoDepthScale: ['far:f32', 'f32'],
  shadowOrthoDepthOffset: ['far:f32', 'f32'],
  shadowConeHalfAngle: ['chord:f32', 'halfFov:f32', 'f32'],
  shadowSunEye: ['r:f32', 'u:f32', 'f:f32', 'x:f32', 'y:f32', 'zNear:f32', 'f32'],
  shadowAlong: ['p:f32', 'd:f32', 's:f32', 'f32'],
  shadowBoxMid: ['low:f32', 'high:f32', 'h:f32', 'f32'],
  shadowBoxHalf: ['low:f32', 'high:f32', 'h:f32', 'f32'],
  shadowNeedKey: ['rank:i32', 'entry:i32', 'i32'],
  shadowEvictionKey: ['age:i32', 'rank:i32', 'page:i32', 'i32'],
  shadowReadableWord: ['page:u32', 'range:u32', 'u32'],
};

/** The WGSL names of the page model's functions: what a test running the shaders in Node lists. */
export const PAGE_MODEL_FUNCTIONS = Object.keys(SIGNATURES) as Array<keyof PageModel<string>>;
