export function cases(THREE) {
  return [
    { name: 'white matte', color: 0xffffff, roughness: 1, metalness: 0 },
    { name: 'grey matte', color: 0x808080, roughness: 1, metalness: 0 },
    { name: 'metal', color: 0x808080, roughness: 0.5, metalness: 1 },
    { name: 'red', color: 0x993322, roughness: 0.5, metalness: 0 },
    { name: 'external ORM', color: 0x808080, roughness: 1, metalness: 1, externalOrm: true },
    { name: 'occlusion', color: 0x808080, roughness: 1, metalness: 0, occlusion: true },
    { name: 'emission', color: 0x111111, roughness: 1, metalness: 0, emissive: 0x881100 },
    { name: 'minified texture', color: 0xffffff, roughness: 1, metalness: 0, minified: true },
    {
      name: 'normal scale XY',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'scale',
    },
    {
      name: 'mirrored normal UV',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'mirror',
    },
    {
      name: 'authored tangents',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'tangent',
    },
    {
      name: 'transparent authored tangents',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'tangent',
      transparent: true,
      opacity: 0.8,
    },
    {
      name: 'near-plane normal',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'clipped',
      side: THREE.DoubleSide,
    },
    {
      name: 'grazing normal',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'grazing',
    },
    {
      name: 'back face normal',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'back',
    },
    {
      name: 'transparent back face normal',
      color: 0x808080,
      roughness: 0.8,
      metalness: 0,
      normalTest: 'back',
      transparent: true,
      opacity: 0.8,
    },
    {
      name: 'transparent PBR',
      color: 0x808080,
      roughness: 1,
      metalness: 0,
      transparent: true,
      opacity: 0.5,
    },
    {
      name: 'transparent ORM',
      color: 0x808080,
      roughness: 1,
      metalness: 1,
      transparent: true,
      opacity: 0.8,
      externalOrm: true,
    },
  ];
}
