import test from 'node:test';import assert from 'node:assert/strict';
import {createGpuPageCache} from './gpuPages.ts';
function mockDevice(limits:Record<string,number>={maxBufferSize:1024}){
 const writes:Array<{offset:number;bytes:Uint8Array}>=[];let fences=0,destroyed=0;
 const device={limits,createBuffer:()=>({destroy(){destroyed++;}}),queue:{writeBuffer:(_buffer:unknown,offset:number,data:Uint8Array)=>writes.push({offset,bytes:new Uint8Array(data)}),onSubmittedWorkDone:async()=>{fences++;}}};
 return {device:device as unknown as GPUDevice,writes,fences:()=>fences,destroyed:()=>destroyed};
}
test('reused GPU slots are cleared through the complete fixed-size slot',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device,writes}=mockDevice();const source={read:async(key:string)=>new Uint8Array(key==='large'?[1,2,3,4,5,6,7,8]:[9,10,11,12])};const cache=createGpuPageCache(device,source,{pageBytes:8,slots:1});await cache.load('large');await cache.load('small');assert.equal(writes.length,2);assert.deepEqual([...writes[1].bytes],[9,10,11,12,0,0,0,0]);assert.equal(cache.stats().uploadedBytes,16);});
test('a cache hit does not fence the whole GPU device',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device,writes,fences}=mockDevice();const cache=createGpuPageCache(device,{read:async()=>new Uint8Array([1,2,3,4])},{pageBytes:8,slots:1});await cache.load('a');const afterLoad=fences();await cache.load('a');assert.equal(fences(),afterLoad);assert.equal(writes.length,1);});
test('page fetches overlap while GPU uploads stay ordered',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device,writes}=mockDevice({maxBufferSize:1024});let current=0,peak=0;const source={read:async()=>{current++;peak=Math.max(peak,current);await Promise.resolve();current--;return new Uint8Array([1,2,3,4]);}};const cache=createGpuPageCache(device,source,{pageBytes:8,slots:2});await Promise.all([cache.load('a'),cache.load('b')]);assert.equal(peak,2);assert.equal(writes.length,2);assert.notEqual(writes[0].offset,writes[1].offset);});
test('storage binding size is rejected before buffer creation',()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});assert.throws(()=>createGpuPageCache({limits:{maxBufferSize:1024,maxStorageBufferBindingSize:8},createBuffer:()=>{throw new Error('should not allocate');},queue:{}} as unknown as GPUDevice,{read:async()=>new Uint8Array(4)},{pageBytes:8,slots:2}),/INVALID_PAGE_BUDGET/);});
test('dispose aborts an in-flight load and does not write after destroy',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device,writes,destroyed}=mockDevice();let resume!:()=>void;const source={read:async(_key:string,signal?:AbortSignal)=>new Promise<Uint8Array>((resolve,reject)=>{const fail=()=>reject(signal?.reason??new Error('aborted'));signal?.addEventListener('abort',fail,{once:true});if(signal?.aborted){fail();return;}resume=()=>resolve(new Uint8Array([1,2,3,4]));})};const cache=createGpuPageCache(device,source,{pageBytes:8,slots:1});const pending=cache.load('a');const closed=cache.dispose();resume?.();await assert.rejects(pending);await closed;assert.equal(writes.length,0);assert.equal(destroyed(),1);});
test('unload releases an unpinned slot so later loads can reuse it',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device,writes}=mockDevice();const cache=createGpuPageCache(device,{read:async()=>new Uint8Array([1,2,3,4])},{pageBytes:8,slots:1});await cache.load('a');assert.equal(cache.unload('a'),true);assert.equal(cache.get('a'),undefined);await cache.load('b');assert.equal(writes.length,2);});
test('an aborted concurrent load does not prevent a separate non-aborted load for the same key',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device,writes}=mockDevice();const controller=new AbortController();const source={read:async(_key:string,signal?:AbortSignal)=>{if(signal?.aborted)throw signal.reason??new Error('aborted');return new Promise<Uint8Array>((resolve,reject)=>{const fail=()=>reject(signal?.reason??new Error('aborted'));signal?.addEventListener('abort',fail,{once:true});setTimeout(()=>resolve(new Uint8Array([1,2,3,4])),10);});}};const cache=createGpuPageCache(device,source,{pageBytes:8,slots:1});const load1=cache.load('a',controller.signal);const load2=cache.load('a');controller.abort(new Error('abort load1'));await assert.rejects(load1,/abort load1/);const page=await load2;assert.equal(page.key,'a');assert.equal(writes.length,1);});

test('GPU diagnostics expose queue, read, upload, pins and eviction while observer errors stay isolated',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device}=mockDevice();const events:string[]=[];const cache=createGpuPageCache(device,{read:async()=>new Uint8Array([1,2,3,4])},{pageBytes:8,slots:1,onDiagnostic:event=>{events.push(event.phase);throw new Error('observer failure');}});const first=await cache.load('a');await cache.load('a');cache.pin('a');assert.equal(cache.unload('a'),false);cache.unpin('a');assert.equal(cache.unload('a'),true);assert.ok(events.includes('gpu-page-catalogue'));assert.ok(events.includes('gpu-page-queue-wait'));assert.ok(events.includes('gpu-page-read-end'));assert.ok(events.includes('gpu-page-upload'));assert.ok(events.includes('gpu-page-cache-hit'));assert.ok(events.includes('gpu-page-pin'));assert.ok(events.includes('gpu-page-unload-refused'));assert.equal(first.generation,1);await cache.dispose();});

test('GPU page read retries once and reports the failed status without changing the load result',async()=>{Object.assign(globalThis,{GPUBufferUsage:{STORAGE:1,COPY_DST:2,COPY_SRC:4}});const {device}=mockDevice();let attempts=0;const phases:Array<{phase:string;context:Record<string,unknown>}>=[];const cache=createGpuPageCache(device,{read:async()=>{attempts++;if(attempts===1)throw new Error('PAGE_HTTP_503');return new Uint8Array([1,2,3,4]);}},{pageBytes:8,slots:1,onDiagnostic:event=>phases.push(event)});const page=await cache.load('retry');assert.equal(page.key,'retry');assert.equal(attempts,2);assert.ok(phases.some(event=>event.phase==='gpu-page-retry'));assert.ok(phases.some(event=>event.phase==='gpu-page-attempt-end'&&event.context.status===503));await cache.dispose();});
