#!/usr/bin/env node
/**
 * Build the witness entry beside the product: `bench/witnesses/measurement.ts` bundled alone into
 * `dist/witnesses/measurement.js`. Only the witness sources are folded in; every engine module they
 * name stays external and points at the file `tsc` already emitted under `dist/`, so a page that
 * loads the witness entry shares one engine instance with it. The host library stays a bare
 * specifier the page's import map resolves. The package's `files` leave `dist/witnesses` out: the
 * published package names no host library (issue #275).
 */
import { build, type Plugin } from 'esbuild';
import { relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const packages = resolve(root, 'packages');
const outdir = resolve(root, 'dist/witnesses');

/** An engine source, resolved from a witness, becomes the address of its emitted file under `dist/`. */
const engineInDist: Plugin = {
  name: 'engine-in-dist',
  setup(bundler) {
    bundler.onResolve({ filter: /^\.\.?\// }, ({ path, resolveDir }) => {
      const target = resolve(resolveDir, path);
      if (!target.startsWith(packages + sep)) return undefined;
      const emitted = resolve(root, 'dist', relative(packages, target))
        .replace(/\.ts$/, '.js')
        .replace(/\.mts$/, '.mjs');
      const address = relative(outdir, emitted).split(sep).join('/');
      return { path: address.startsWith('.') ? address : `./${address}`, external: true };
    });
  },
};

await build({
  absWorkingDir: root,
  entryPoints: { measurement: 'bench/witnesses/measurement.ts' },
  outdir,
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  external: ['three', 'three/*'],
  plugins: [engineInDist],
  banner: { js: '// Generated by scripts/build-witnesses.ts. Bench only: never published.' },
  logLevel: 'warning',
});
