import test from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { commitProblem, type Commit } from './check-commit-identity.ts';

const maintainer = { name: 'Alban Pasquelin', email: 'alban@example.org' };
const commit = (
  message: string,
  author: { name?: string; email?: string } = maintainer,
  committer = author,
  sha = 'a1b2c3d4e5',
): Commit => ({ sha, commit: { message, author, committer } });

test('check-commit-identity: a tool author is refused and its hash named', () => {
  const problem = commitProblem([
    commit('Fix the tangents', { name: 'Claude', email: 'noreply@anthropic.com' }),
  ]);
  assert.match(problem ?? '', /a1b2c3d4e5: /);
  assert.match(problem ?? '', /noreply@anthropic\.com/);
  // The committer is read too, by name or by a tool host in the address.
  assert.match(
    commitProblem([commit('Fix', maintainer, { name: 'GitHub Copilot', email: 'x@y.org' })]) ?? '',
    /committer name "GitHub Copilot" names a tool/,
  );
  assert.match(
    commitProblem([commit('Fix', maintainer, { email: 'copilot@github.com' })]) ?? '',
    /copilot@github\.com/,
  );
  assert.match(
    commitProblem([commit('Fix', { email: 'claude@anthropic.com' })]) ?? '',
    /names a tool/,
  );
});

test('check-commit-identity: a Co-authored-by or a Generated trailer is refused', () => {
  assert.match(
    commitProblem([commit('Fix\n\nCo-authored-by: Claude <noreply@anthropic.com>')]) ?? '',
    /a1b2c3d4e5: .*"Co-authored-by:" trailer/,
  );
  assert.match(
    commitProblem([commit('Fix\n\nGenerated with [Claude Code]')]) ?? '',
    /"Generated with" trailer/,
  );
  assert.match(
    commitProblem([commit('Fix\n\nGenerated by an assistant')]) ?? '',
    /"Generated with" trailer/,
  );
});

test('check-commit-identity: a plain maintainer commit passes, every offender is listed', () => {
  assert.equal(commitProblem([commit('Fix the tangents scaling')]), undefined);
  // A human address on a human host is never refused, even with a tool word in it.
  assert.equal(
    commitProblem([commit('Fix', { name: 'Alban Pasquelin', email: 'claude@gmail.com' })]),
    undefined,
  );
  const problem =
    commitProblem([
      commit('one\n\nCo-authored-by: X <x@y.org>', maintainer, maintainer, 'aaa'),
      commit('two\n\nGenerated with X', maintainer, maintainer, 'bbb'),
    ]) ?? '';
  assert.match(problem, /aaa: /);
  assert.match(problem, /bbb: /);
});

test('check-commit-identity: the CLI reads PR_NUMBER, and throws without a token in the CI', () => {
  const script = new URL('check-commit-identity.ts', import.meta.url).pathname;
  const run = (env: Record<string, string>) =>
    spawnSync(process.execPath, [script], {
      encoding: 'utf8',
      env: { PATH: process.env.PATH, ...env },
    });
  // A push event names no pull request: nothing to refuse, exit 0.
  const push = run({});
  assert.equal(push.status, 0);
  assert.equal(push.stderr, '');
  const tokenless = run({ PR_NUMBER: '1', CI: 'true' });
  assert.equal(tokenless.status, 1);
  assert.match(tokenless.stderr, /GITHUB_TOKEN and GITHUB_REPOSITORY are required/);
});
