// Refuses a commit that carries a tool identity: an author or committer named after an assistant
// tool, or carrying a tool's email, and a message with a `Co-authored-by:` or a `Generated with` /
// `Generated by` trailer (AGENTS.md rule 9). The pull request's commits are read from the REST API
// and the reason names every offending hash, one per line, so the CI names them all.
// Usage: PR_NUMBER=… GITHUB_TOKEN=… GITHUB_REPOSITORY=owner/repo node scripts/check-commit-identity.ts
import { pathToFileURL } from 'node:url'
import { githubApi } from './github-api.ts'

/** A commit as the REST API returns it, the fields the check reads. */
export interface Commit {
  sha: string
  commit: { message: string; author?: Person; committer?: Person }
}

/** An author or a committer, as the REST API names it. */
export type Person = { name?: string; email?: string }

/** The assistant tools a name or an email local part must not carry, case-insensitive, as a word. */
const TOOLS = ['claude', 'copilot', 'cursor', 'codex', 'aider', 'devin', 'chatgpt', 'openai']
const TOOL_NAME = new RegExp(`\\b(?:${TOOLS.join('|')})\\b`, 'i')

/** The vendors a tool commits under: a tool host with no tool name in it is a person's address. */
const TOOL_HOST = /@(?:anthropic\.com|openai\.com|github\.com)$/i

/** The `noreply@anthropic.com` bot address, refused whatever the name it carries. */
const TOOL_EMAIL = 'noreply@anthropic.com'

/** A tool's "Generated with" / "Generated by" signature, at the start of a line, any case: refused
 *  in a commit message here and in a pull request body (`check-pr-body.ts`). */
export const GENERATED_FOOTER = /^[^\S\n]*(?:🤖\s*)?generated (?:with|by)\b/im

/** The tool trailer a message must not carry, at the start of a line, any case. */
const TRAILERS = [
  { pattern: /^[^\S\n]*co-authored-by:/im, why: 'a "Co-authored-by:" trailer' },
  { pattern: GENERATED_FOOTER, why: 'a "Generated with" trailer' },
]

/** Why one author or committer carries a tool identity, or undefined. */
function identityProblem(role: string, person?: Person): string | undefined {
  if (!person) return undefined
  const email = (person.email ?? '').toLowerCase()
  const name = person.name ?? ''
  if (email === TOOL_EMAIL) return `the ${role} email is ${TOOL_EMAIL}`
  const local = email.split('@')[0]
  if (TOOL_HOST.test(email) && TOOL_NAME.test(local))
    return `the ${role} email ${email} names a tool`
  if (TOOL_NAME.test(name)) return `the ${role} name "${name}" names a tool`
  return undefined
}

/** Why one message carries a refused trailer, or undefined. */
function trailerProblem(message: string): string | undefined {
  return TRAILERS.find(({ pattern }) => pattern.test(message))?.why
}

/**
 * The reason the commits carry a tool identity or a trailer (AGENTS.md rule 9), every offending
 * hash named one per line, or undefined when they all pass.
 */
export function commitProblem(commits: Commit[]): string | undefined {
  const problems: string[] = []
  for (const { sha, commit } of commits) {
    const why = [
      identityProblem('author', commit.author),
      identityProblem('committer', commit.committer),
      trailerProblem(commit.message),
    ].filter((reason): reason is string => reason !== undefined)
    if (why.length) problems.push(`${sha}: ${why.join('; ')}`)
  }
  return problems.length
    ? `A commit carries a tool identity or a trailer (AGENTS.md rule 9):\n${problems.join('\n')}`
    : undefined
}

/** The commits of a pull request, every page: a page short of `PER_PAGE` is the last. */
async function pullCommits(repo: string, token: string, number: string): Promise<Commit[]> {
  const PER_PAGE = 100
  const api = githubApi(repo, token)
  const commits: Commit[] = []
  for (let page = 1; ; page += 1) {
    const batch = await api<Commit[]>(`pulls/${number}/commits?per_page=${PER_PAGE}&page=${page}`)
    commits.push(...batch)
    if (batch.length < PER_PAGE) return commits
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const { PR_NUMBER: number, GITHUB_TOKEN: token, GITHUB_REPOSITORY: repo, CI } = process.env
  // A push event names no pull request: nothing to read, nothing to refuse.
  if (number) {
    if (!token || !repo) {
      if (CI) throw new Error('GITHUB_TOKEN and GITHUB_REPOSITORY are required in the CI.')
      console.error('Commits not checked: no GITHUB_TOKEN or GITHUB_REPOSITORY.')
    } else {
      const problem = commitProblem(await pullCommits(repo, token, number))
      if (problem) {
        console.error(problem)
        process.exitCode = 1
      }
    }
  }
}
