import {
  analyzeEntries,
  consumerImports,
  ENTRIES,
  type ExportEntry,
  type ExportRow,
  writeGenerated,
} from './sdk-api-model.ts';
import { DOCUMENTED_GAPS } from './sdk-api-documented.ts';

const rows = analyzeEntries();
const consumers = consumerImports();
rows.push(...DOCUMENTED_GAPS);

// Categories follow the folders of `packages/sdk-core/src/`: each facade file re-exports one area.
const CATEGORY_RULES: [string, RegExp][] = [
  ['llm', /\/llm\//],
  [
    'diagnostics',
    /\/math\/oracles\.ts$|\/runtime\/(?:diagnostics|stats|stageProfile|competitors|compareImages|paths)\.ts$|\/contracts\/metrics\.ts$/,
  ],
  ['math', /\/src\/(?:math|hiz|world\/math)\//],
  ['lighting', /\/src\/(?:lighting|bounce|scene\/light(?:-shadow)?)\/|\/contracts\/proxy\.ts$/],
  [
    'streaming',
    /\/src\/(?:manifest\/|page\/(?!contracts\.ts)|texture\/)|\/contracts\/(?:geometry|cache)\.ts$/,
  ],
  ['lifecycle', /\/runtime\/(?:jobs|safety|events)\.ts$|\/contracts\/base\.ts$/],
];

function category(row: ExportRow): string {
  return CATEGORY_RULES.find(([, pattern]) => pattern.test(row.module))?.[0] ?? 'contracts';
}

function classification(row: ExportRow): string {
  return /\/math\/oracles\.ts$|competitors|compareImages|experiment[A-Z]|screenErrorVariant/.test(
    row.module,
  )
    ? 'experimental'
    : 'public';
}

function environments(row: ExportRow): string {
  if (row.entries.includes('core')) return 'common, browser, node, worker';
  if (row.entries.includes('browser')) return 'browser';
  return 'node';
}

function sourceFor(row: ExportRow, facade: string): string {
  const depth = facade.includes('sdk-core/src/index') || facade === 'nested' ? '../../' : '../';
  return `${depth}${row.module.slice('packages/'.length)}`;
}

function exportLines(selected: ExportRow[], source: string): string {
  const lines = ['// Generated by scripts/generate-sdk-facade.ts.'];
  for (const module of [...new Set(selected.map((row) => sourceFor(row, source)))]) {
    const group = selected.filter((row) => sourceFor(row, source) === module);
    const values = group.filter((row) => row.kind !== 'type').map((row) => row.name);
    const types = group.filter((row) => row.kind === 'type').map((row) => row.name);
    if (values.length) lines.push(`export {\n  ${values.join(',\n  ')},\n} from '${module}';`);
    if (types.length) lines.push(`export type {\n  ${types.join(',\n  ')},\n} from '${module}';`);
  }
  return `${lines.join('\n')}\n`;
}

const common = rows.filter((row) => row.entries.includes('core'));
const categories = [...new Set(common.map(category))].sort();
for (const name of categories)
  await writeGenerated(
    `packages/sdk/common/${name}.ts`,
    exportLines(
      common.filter((row) => category(row) === name),
      '../../sdk-core/src/index.ts',
    ),
  );
await writeGenerated(
  'packages/sdk/common/index.ts',
  `${categories.map((name) => `export * from './${name}.ts';`).join('\n')}\n`,
);

const browserOnly = rows.filter(
  (row) => row.entries.includes('browser') && !row.entries.includes('core'),
);
// The browser-only exports: the world and its families written here, where they win over the
// common names they shadow (`Scene`, `Material`…); the rest of the engine in a file of its own,
// which a single facade outgrew the line gate of every maintained source with.
const worldModule = (row: ExportRow) => /\/world\//.test(row.module);
await writeGenerated(
  'packages/sdk/browser/engine.ts',
  exportLines(
    browserOnly.filter((row) => !worldModule(row)),
    'nested',
  ),
);
await writeGenerated(
  'packages/sdk/browser.ts',
  `export * from './common/index.ts';\nexport * from './browser/engine.ts';\n${exportLines(
    browserOnly.filter(worldModule),
    '../sdk-browser/src/index.ts',
  )}`,
);
const nodeOnly = rows.filter(
  (row) => row.entries.includes('node') && !row.entries.includes('core'),
);
await writeGenerated(
  'packages/sdk/node.mts',
  `export * from './common/index.ts';\n${exportLines(nodeOnly, '../sdk-node/src/index.mts')}`,
);
await writeGenerated('packages/sdk/index.ts', "export * from './common/index.ts';\n");

const entryLabel: Record<ExportEntry, string> = {
  core: 'web-geometry (common)',
  browser: 'web-geometry (browser condition)',
  node: 'web-geometry (node condition)',
};

interface InventoryEntry {
  name: string;
  kind: ExportRow['kind'];
  definingModule: string;
  currentEntryPoints: string[];
  proposedEnvironments: string;
  classification: string;
  affectedConsumers: string[];
  disposition: string;
  bindingIdentity: string;
}

const inventory: InventoryEntry[] = rows.map((row) => ({
  name: row.name,
  kind: row.kind,
  definingModule: row.module,
  currentEntryPoints: row.entries.map((entry) => entryLabel[entry]),
  proposedEnvironments: environments(row),
  classification: classification(row),
  affectedConsumers: [...(consumers.get(row.name) ?? []), ...(row.consumers ?? [])].sort(),
  disposition: row.disposition ?? 'retained',
  bindingIdentity: row.identity,
}));
// `Object.groupBy` needs lib ES2024, beyond the tools' configured lib: grouped by hand instead,
// in the same first-seen order.
const grouped = new Map<string, InventoryEntry[]>();
for (const entry of inventory) {
  const group = grouped.get(entry.name) ?? [];
  group.push(entry);
  grouped.set(entry.name, group);
}
// A name bound twice is a collision, unless one binding is a page word of the world families
// (`packages/*/world/`) and the other an engine contract of the common entry: the browser facade
// names the page word explicitly, and an explicit export shadows the common one there. Those are
// listed apart, so the shadowing is a decision the inventory states, not an accident.
const collisions: { name: string; bindings: string[] }[] = [],
  shadowed: { name: string; bindings: string[] }[] = [];
for (const [name, entries] of grouped) {
  const bindings = entries.map((entry) => entry.bindingIdentity);
  if (new Set(bindings).size < 2) continue;
  const words = entries.filter((entry) => entry.definingModule.includes('/world/'));
  const pageWord =
    entries.length === 2 &&
    words.length === 1 &&
    entries.some((entry) => entry.currentEntryPoints.includes(entryLabel.core));
  (pageWord ? shadowed : collisions).push({ name, bindings });
}
await writeGenerated(
  'site/data/api-inventory.json',
  `${JSON.stringify({ generatedFrom: ENTRIES, collisions, shadowed, exports: inventory }, null, 2)}\n`,
);
