import { posix } from 'node:path';
import { analyzeEntries, type ExportRow, writeGenerated } from './sdk-api-model.ts';
import { DOCUMENTED_GAPS } from './sdk-api-documented.ts';

const rows = [...analyzeEntries(), ...DOCUMENTED_GAPS];

// Categories follow the folders of `packages/sdk-core/src/`: each facade file re-exports one area.
const CATEGORY_RULES: [string, RegExp][] = [
  ['llm', /\/llm\//],
  [
    'diagnostics',
    /\/math\/oracles\.ts$|\/runtime\/(?:diagnostics|stats|stageProfile|competitors|compareImages|paths)\.ts$|\/contracts\/metrics\.ts$/,
  ],
  ['math', /\/src\/(?:math|hiz|world\/math)\//],
  ['lighting', /\/src\/(?:lighting|bounce|scene\/light(?:-shadow)?)\/|\/contracts\/proxy\.ts$/],
  [
    'streaming',
    /\/src\/(?:manifest\/|page\/(?!contracts\.ts)|texture\/)|\/contracts\/(?:geometry|cache)\.ts$/,
  ],
  ['lifecycle', /\/runtime\/(?:jobs|safety|events)\.ts$|\/contracts\/base\.ts$/],
];

function category(row: ExportRow): string {
  return CATEGORY_RULES.find(([, pattern]) => pattern.test(row.module))?.[0] ?? 'contracts';
}

/** The path `facade` imports `row` by, relative to the facade's own folder. */
function sourceFor(row: ExportRow, facade: string): string {
  const path = posix.relative(posix.dirname(facade), row.module);
  return path.startsWith('.') ? path : `./${path}`;
}

/** The export statements of `selected` as the generated file `facade` writes them. */
function exportLines(selected: ExportRow[], facade: string): string {
  const lines = ['// Generated by scripts/generate-sdk-facade.ts.'];
  for (const module of [...new Set(selected.map((row) => sourceFor(row, facade)))]) {
    const group = selected.filter((row) => sourceFor(row, facade) === module);
    const values = group.filter((row) => row.kind !== 'type').map((row) => row.name);
    const types = group.filter((row) => row.kind === 'type').map((row) => row.name);
    if (values.length) lines.push(`export {\n  ${values.join(',\n  ')},\n} from '${module}';`);
    if (types.length) lines.push(`export type {\n  ${types.join(',\n  ')},\n} from '${module}';`);
  }
  return `${lines.join('\n')}\n`;
}

const common = rows.filter((row) => row.entries.includes('core'));
const categories = [...new Set(common.map(category))].sort();
for (const name of categories)
  await writeGenerated(
    `packages/sdk/common/${name}.ts`,
    exportLines(
      common.filter((row) => category(row) === name),
      `packages/sdk/common/${name}.ts`,
    ),
  );
await writeGenerated(
  'packages/sdk/common/index.ts',
  `${categories.map((name) => `export * from './${name}.ts';`).join('\n')}\n`,
);

const browserOnly = rows.filter(
  (row) => row.entries.includes('browser') && !row.entries.includes('core'),
);
// The browser facade is split like the common one, by area — the page words of the world families
// apart from the engine's other browser exports — so no generated file outgrows the line limit. A
// page word that shadows a common contract of the same name is named explicitly in
// `browser.ts`: two star exports of one name would cancel each other, an explicit one wins.
const browserArea = (row: ExportRow) => (/\/world\//.test(row.module) ? 'world' : 'engine');
const commonNames = new Set(common.map((row) => row.name));
const browserAreas = [...new Set(browserOnly.map(browserArea))].sort();
for (const name of browserAreas)
  await writeGenerated(
    `packages/sdk/browser/${name}.ts`,
    exportLines(
      browserOnly.filter((row) => browserArea(row) === name),
      `packages/sdk/browser/${name}.ts`,
    ),
  );
const shadowing = browserOnly
  .filter((row) => commonNames.has(row.name))
  .map((row) => ({ ...row, module: `packages/sdk/browser/${browserArea(row)}.ts` }));
await writeGenerated(
  'packages/sdk/browser.ts',
  [
    "export * from './common/index.ts';",
    ...browserAreas.map((name) => `export * from './browser/${name}.ts';`),
    exportLines(shadowing, 'packages/sdk/browser.ts'),
  ].join('\n'),
);
const nodeOnly = rows.filter(
  (row) => row.entries.includes('node') && !row.entries.includes('core'),
);
await writeGenerated(
  'packages/sdk/node.mts',
  `export * from './common/index.ts';\n${exportLines(nodeOnly, 'packages/sdk/node.mts')}`,
);
await writeGenerated('packages/sdk/index.ts', "export * from './common/index.ts';\n");
